== What is Cython

Cython is a programming language that makes writing C extensions for the
Python language as easy as Python itself.

It is used in lib-common by IOPy, see `iopy/README.adoc`, and PXCC exports C
types and symbols to Cython files, see `pxcc/README.adoc`.

The first thing to do before using Cython is to read the offical
documentation: https://cython.readthedocs.io/

== Cython source files in Lib-common

The directory `src` is added to the include directories in
`CYTHONFLAGS` on `waf configure`.
To include lib-common Cython source files, the following syntax should be
used:
[source,python]
----
from libcommon_cython.xxx cimport *
----

Cython source files in Lib-common are split in a similar way as the C source
files.

For a `feature` included in a Cython `module`, we can have the different
source files:

- `feature.pxc`: PXCC file that defines automatic binding between C types and
                 symbols to Cython.
                 See `pxcc/README.md` for more information on PXCC.
                 The build system, on `waf build`, creates, from a PXCC file
                 `feature.pxc`, a Cython definition file named
                 `feature_pxc.pxd` that can be imported by Cython source
                 files.

- `feature.h`: Special C header for the Cython feature. It is typically used
               to export macros that can not be exported strait-forward with
               PXCC.

- `feature.pxd`: Cython source file of the feature. Imports the Cython
                 definition file from PXCC `feature_pxc.pxd`, and defines the
                 types and symbols of `feature.h`.

- `module.pyx`: Cython module source file. Used by Cython as main source file
                to generate the Python extension. It imports the source file
                of the feature `feature.pxd`.

== Cython fixes

Unfortunately, there are some macros conflicts between the code generated by
Cython and Lib-common.
To solve this the Cython source file `cython_fixes.pxd` must be imported after
all the imports and includes in a Cython module when using Lib-common.
