#!/bin/bash -eu
###########################################################################
#                                                                         #
# Copyright 2026 INTERSEC SA                                              #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#     http://www.apache.org/licenses/LICENSE-2.0                          #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
#                                                                         #
###########################################################################
#
# Template to generate .tool-versions file.
# LIBCOMMON_DIR and REPO_DIR variables are set by asdf_install.sh

# Use the system python version when it is at least 3.11, the version shipped
# by the oldest OS supported by this branch. Use ASDF to get Python 3.11.14
# otherwise.
#
# No maximum is set here, unlike on the stable branches: a machine more recent
# than any OS we support, such as a developer laptop, then builds with a python
# version we do not ship yet, and reports the breaking changes of a new python
# release early. The stable branches cannot afford that, since they must stick
# to the versions their OSes ship.
#
# It is possible to manually set the different environment variables
# TOOL_VERSIONS_PYTHON, TOOL_VERSIONS_DEFAULT_PYTHON, TOOL_VERSIONS_MIN_PYTHON
# and TOOL_VERSIONS_MAX_PYTHON for some customization of .tool-versions.
#
# `asdf shell python ...` and `$ASDF_PYTHON_VERSION` still override the
# configured version in .tool-versions.
TOOL_VERSIONS_PYTHON="${TOOL_VERSIONS_PYTHON:-"$( \
    "$LIBCOMMON_DIR/build/asdf_python_version.sh" \
    "${TOOL_VERSIONS_DEFAULT_PYTHON:-3.11.14}" \
    "${TOOL_VERSIONS_MIN_PYTHON:-3.11.0}" \
    "${TOOL_VERSIONS_MAX_PYTHON:-}" \
)"}"

cat <<EOF
# THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY
#
# ASDF configuration file for lib-common repository.
#
# https://asdf-vm.com/manage/configuration.html

python $TOOL_VERSIONS_PYTHON
uv 0.7.2
rust 1.92.0
EOF
