strategy:
  matrix:
    ubuntu-20.04:
      imageName: "ubuntu-20.04"

    ubuntu-22.04:
      imageName: "ubuntu-22.04"

  maxParallel: 3

pool:
  vmImage: $(imageName)

steps:
  - bash: |
      sudo apt-get update && \
      sudo apt-get install \
        clang \
        curl \
        exuberant-ctags \
        flex \
        gperf \
        libclang-dev \
        libssl-dev \
        libxml2-dev \
        llvm-dev \
        pkg-config \
        python3-dev \
        python3-pip \
        smitools \
        snmp-mibs-downloader \
        valgrind
    displayName: Install system dependencies

  - bash: |
      sudo python3 -m pip install --upgrade pip && \
      sudo python3 -m pip install virtualenv
    displayName: Update pip and install virtualenv

  - script: |
      curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
      echo "##vso[task.setvariable variable=PATH]${PATH}:$HOME/.poetry/bin"
    displayName: Install poetry

  - bash: |
      sudo curl https://waf.io/waf-2.0.20 -o /usr/local/bin/waf && \
      sudo chmod +x /usr/local/bin/waf && \
      sudo waf --help 2>&1 >/dev/null
    displayName: Install waf

  - script: waf configure
    displayName: Configure with GCC, default

  - script: waf build
    displayName: Compile with GCC, default

  - script: waf check
    displayName: Check with GCC, default

  - script: waf clean
    displayName: Clean-up

  - script: waf configure
    env:
      CC: 'clang'
      CXX: 'clang++'
      P: 'asan'
    displayName: Configure with Clang, ASan

  - script: waf build
    displayName: Compile with Clang, ASan

  - script: waf check
    env:
      ASAN_OPTIONS: 'handle_segv=0:detect_leaks=1'
    displayName: Check with Clang, ASan

  - script: waf pylint
    displayName: Check with pylint
