###########################################################################
#                                                                         #
# Copyright 2021 INTERSEC SA                                              #
#                                                                         #
# Licensed under the Apache License, Version 2.0 (the "License");         #
# you may not use this file except in compliance with the License.        #
# You may obtain a copy of the License at                                 #
#                                                                         #
#     http://www.apache.org/licenses/LICENSE-2.0                          #
#                                                                         #
# Unless required by applicable law or agreed to in writing, software     #
# distributed under the License is distributed on an "AS IS" BASIS,       #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.#
# See the License for the specific language governing permissions and     #
# limitations under the License.                                          #
#                                                                         #
###########################################################################
#
# XXX: When adding packages here, you must call `poetry update` in order to
# update poetry.lock.
# Otherwise, `waf configure` will fail.

[tool.poetry]
name = "lib-common"
version = "0.0.0"
description = ""
authors = ["R&D <rd@intersec.com>"]

[tool.poetry.dev-dependencies]
# C extension writer for Python, used by IOPy
cython = "==0.29.24"

# process handling, used in tests
psutil = "~=5.0.0"

# behaviour-driven developement, used in tests
behave = "==1.2.6"

# interactive debugger, for debugging
ipdb = "~=0.12.0"

# python linter
pylint = "==2.4.4"

# array computing, used in benchmarks.
numpy = "~=1.18.0"

# 2D graphics, used in benchmarks.
matplotlib = "~=3.0.0"

[tool.poetry.dependencies]
# Require at least Python version 3.5
python = "^3.5"
