Intersec waf-based build system
================================

Introduction
------------

Intersec build system uses waf (https://waf.io/). If you want to understand
how it works, you should read the Waf Book (https://waf.io/book/), but this
is not necessary if you just want to use it.

All the Intersec specificities and custom rules are defined in waf tools,
located in the `waftools` directory.

The main entry point of the build system is the `wscript` file located at
top-level of the repository. It loads the Intersec tools, defines the main
`configure` and `build` functions, and recurses in sub-directories (that
contain their own `wscript` or `wscript_build` files).

The waftools and wscript files are supposed to be readable and documented when
needed.


How to build?
-------------

First of all, you have to configure your project, by running in the top-level
directory:
---------------------------------
$ waf configure [--prefix=PREFIX]
---------------------------------

The installation prefix is controlled with the option `--prefix`.
It is important to set it when you want to install the tools for example.
This option will set the environment variable `${PREFIX}` in the wscript
files.


If the configuration step triggers no error, then you are ready to build,
which just consists in running:
----------------------------------
$ waf
or
$ waf build
----------------------------------

You can run it from a sub-directory in order to build only the targets defined
in this directory and its sub-directories (and its dependencies).

All the available targets can be listed with this command:
----------------------------------
$ waf list
----------------------------------

It is possible to build only a specific target, or a list of targets, by
running, from anywhere in the repository:
----------------------------------
$ waf --targets=target1,target2
----------------------------------

NOTE: several targets have the same name (for example all the `zchk`
      programs), so building a specific one in that case is not really
      supported.


Other Intersec-specific waf commands
------------------------------------

Other commands are listed with `waf --help`. Here they are:

* `waf check`: run the tests of the current directory (defined in the `ZFile`)
               and in its sub-directories.
               The following variants also exist (cf `waf --help` for the
               details): `fast-check`, `www-check`, `selenium`,
               `fast-selenium`.
* `waf tags`: generate tags using ctags.
* `waf etags`: generate tags for emacs using ctags.
* `waf pylint`: run pylint checks on committed python files.
* `old-gen-files-detect`: detect old files generated by a previous build
                          system run.
* `old-gen-files-delete`: delete the files detected by the previous command.
* `coverage-start`: start a coverage session (requires coverage profile).
                    This resets the coverage counters. After running this
                    command, you can run some code and use the `coverage-end`
                    command to produce a coverage report.
                    Note that this is done when configuring the project.
* `coverage-end`: end a coverage session and produce a report.
* `app-delivery`: prepare an APP delivery (archive of the source code)



Environment variables
---------------------

The following environment variables can be used at the configuration phase:

`P` (string)::
    Specify the desired compilation profile (default, debug, release, ...).
    The complete list of available profiles is defined in
    `waftools/backend.py`, variable `PROFILES`.
    If not specified, the default profile is `default`.

`NO_JAVA` (boolean)::
    Set it to disable the Java support.

`NOCHECK` (boolean)::
    The build-system doesn't run "check" targets, which are:
      * clang check of c files.
      * linters on js/ts files.
    You may want to set it to speedup the build.
    You can also bypass the checks thanks to the `nocheck` parameter of
    task-generators, which can be `True` to bypass the checks of all the
    source files, or a list of files to not check.

`NOCOMPRESS` (boolean)::
    If set, the build-system doesn't compress the debug section of binaries
    leading to larger binary files. This can be used if you have to work
    with tools that does not support compressed-debug sections (like
    valgrind, pahole or some old version of gdb).
    You may also want to set it to speedup the build.
    This is ignored in release profile.

`NO_DOUBLE_FPIC` (boolean)::
    If set, the compilation will be faster, but the produced binaries will be
    larger and the runtime performances will be affected.
    Cf. `waftools/backend.py` for the details.
    This is ignored in release profile.

`FAKE_VERSIONS` (boolean)::
    If set, the version files are generated with fake (and constant) data, so
    that changing of git revision does not trigger a re-link of all the
    binaries. This is a huge gain of time, but it's not possible to know the
    revision of the binaries that are built with this flag.
    This is ignored in release profile.

TODOs
-----

* All waf TODOs and FIXMEs can be listed with `$ git grep "TODO waf"` and
  `$ git grep "FIXME waf"`.
