/*****     THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY !    *****/
#ifndef IS_HTTP_TOKENS_H
#define IS_HTTP_TOKENS_H

#include <lib-common/core.h>

enum http_token {
    HTTP_TK_unknown,
    HTTP_TK_CHUNKED,
    HTTP_TK_COMPRESS,
    HTTP_TK_CONNECT,
    HTTP_TK_DEFLATE,
    HTTP_TK_DELETE,
    HTTP_TK_GET,
    HTTP_TK_GZIP,
    HTTP_TK_HEAD,
    HTTP_TK_IDENTITY,
    HTTP_TK_OPTIONS,
    HTTP_TK_POST,
    HTTP_TK_PUT,
    HTTP_TK_TRACE,
    HTTP_TK_X_COMPRESS,
    HTTP_TK_X_GZIP,
};

__attribute__((pure))
enum http_token
http_get_token(const char *s, int len);

__attribute__((pure))
enum http_token
http_get_token_ps(pstream_t ps);

static ALWAYS_INLINE enum http_token
http_get_token_lstr(lstr_t s)
{
    return http_get_token(s.s, s.len);
}
#endif /* IS_HTTP_TOKEN_H */
