/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef linux
#  warning "tstdox.iop assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "tstdox.iop assumed x86_64 alignments"
#endif

#include "tstdox.iop.h"

/* Enum tstdox.MyEnumA {{{ */

static int const tstdox__my_enum_a__values[] = {
 0, 1, 2,
};
static int const iop__ranges__1[] = {
    0, 0,
    3,
};
static const lstr_t tstdox__my_enum_a__names[] = {
    LSTR_IMMED("VAL_A"),
    LSTR_IMMED("VAL_B"),
    LSTR_IMMED("VAL_C"),
};
static const iop_help_t tstdox__my_enum_a__val_a__v_help = {
    .brief = LSTR_IMMED("< comment for MY_ENUM_A_VAL_A"),
};
static const iop_enum_value_attr_t tstdox__my_enum_a__val_a__v_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_value_attr_arg_t[]){ { .v.p = &tstdox__my_enum_a__val_a__v_help } },
    },
};
static const iop_help_t tstdox__my_enum_a__val_c__v_help = {
    .brief = LSTR_IMMED("comment for MY_ENUM_A_VAL_C"),
};
static const iop_enum_value_attr_t tstdox__my_enum_a__val_c__v_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_value_attr_arg_t[]){ { .v.p = &tstdox__my_enum_a__val_c__v_help } },
    },
};
static const iop_enum_value_attrs_t tstdox__my_enum_a__e_desc_values_attrs[] = {
    {
        .flags     = 32,
        .attrs_len = 1,
        .attrs     = tstdox__my_enum_a__val_a__v_attrs,
    },
    {
        .flags     = 0,
    },
    {
        .flags     = 32,
        .attrs_len = 1,
        .attrs     = tstdox__my_enum_a__val_c__v_attrs,
    },
};
static const iop_help_t tstdox__my_enum_a__e_help = {
    .brief = LSTR_IMMED("comment for MyEnumA"),
    .details = LSTR_IMMED("details for MyEnumA \134word not a recognized keyword"),
    .warning = LSTR_IMMED("warn for MyEnumA"),
};
static const iop_enum_attr_t tstdox__my_enum_a__e_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_attr_arg_t[]){ { .v.p = &tstdox__my_enum_a__e_help } },
    },
};
static const iop_enum_attrs_t tstdox__my_enum_a__e_desc_attrs = {
    .flags     = 32,
    .attrs_len = 1,
    .attrs     = tstdox__my_enum_a__e_attrs,
};
iop_enum_t const tstdox__my_enum_a__e = {
    .name         = LSTR_IMMED("MyEnumA"),
    .fullname     = LSTR_IMMED("tstdox.MyEnumA"),
    .names        = tstdox__my_enum_a__names,
    .values       = tstdox__my_enum_a__values,
    .ranges       = iop__ranges__1,
    .ranges_len   = countof(iop__ranges__1) / 2,
    .enum_len     = 3,
    .flags        = 1,
    .en_attrs     = &tstdox__my_enum_a__e_desc_attrs,
    .values_attrs = tstdox__my_enum_a__e_desc_values_attrs,
};
iop_enum_t const * const tstdox__my_enum_a__ep = &tstdox__my_enum_a__e;

/* }}} */
/* Enum tstdox.MyEnumB {{{ */

static int const tstdox__my_enum_b__values[] = {
 0, 1, 2,
};
static const lstr_t tstdox__my_enum_b__names[] = {
    LSTR_IMMED("VAL_A"),
    LSTR_IMMED("VAL_B"),
    LSTR_IMMED("VAL_C"),
};
iop_enum_t const tstdox__my_enum_b__e = {
    .name         = LSTR_IMMED("MyEnumB"),
    .fullname     = LSTR_IMMED("tstdox.MyEnumB"),
    .names        = tstdox__my_enum_b__names,
    .values       = tstdox__my_enum_b__values,
    .ranges       = iop__ranges__1,
    .ranges_len   = countof(iop__ranges__1) / 2,
    .enum_len     = 3,
};
iop_enum_t const * const tstdox__my_enum_b__ep = &tstdox__my_enum_b__e;

/* }}} */
/* Enum tstdox.MyEnumC {{{ */

static int const tstdox__my_enum_c__values[] = {
 0,
};
static int const iop__ranges__2[] = {
    0, 0,
    1,
};
static const lstr_t tstdox__my_enum_c__names[] = {
    LSTR_IMMED("VAL_A"),
};
static const iop_help_t tstdox__my_enum_c__e_help = {
    .brief = LSTR_IMMED("comment for MY_ENUM_C"),
};
static const iop_enum_attr_t tstdox__my_enum_c__e_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_attr_arg_t[]){ { .v.p = &tstdox__my_enum_c__e_help } },
    },
};
static const iop_enum_attrs_t tstdox__my_enum_c__e_desc_attrs = {
    .flags     = 32,
    .attrs_len = 1,
    .attrs     = tstdox__my_enum_c__e_attrs,
};
iop_enum_t const tstdox__my_enum_c__e = {
    .name         = LSTR_IMMED("MyEnumC"),
    .fullname     = LSTR_IMMED("tstdox.MyEnumC"),
    .names        = tstdox__my_enum_c__names,
    .values       = tstdox__my_enum_c__values,
    .ranges       = iop__ranges__2,
    .ranges_len   = countof(iop__ranges__2) / 2,
    .enum_len     = 1,
    .flags        = 3,
    .en_attrs     = &tstdox__my_enum_c__e_desc_attrs,
};
iop_enum_t const * const tstdox__my_enum_c__ep = &tstdox__my_enum_c__e;

/* }}} */
/* Enum tstdox.MyEnumD {{{ */

static int const tstdox__my_enum_d__values[] = {
 0, 1, 2,
};
static const lstr_t tstdox__my_enum_d__names[] = {
    LSTR_IMMED("VAL_A"),
    LSTR_IMMED("VAL_B"),
    LSTR_IMMED("VAL_C"),
};
static const iop_help_t tstdox__my_enum_d__val_b__v_help = {
    .brief = LSTR_IMMED("comment for MY_ENUM_D_VAL_B"),
};
static const iop_enum_value_attr_t tstdox__my_enum_d__val_b__v_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_value_attr_arg_t[]){ { .v.p = &tstdox__my_enum_d__val_b__v_help } },
    },
};
static const iop_enum_value_attrs_t tstdox__my_enum_d__e_desc_values_attrs[] = {
    {
        .flags     = 0,
    },
    {
        .flags     = 32,
        .attrs_len = 1,
        .attrs     = tstdox__my_enum_d__val_b__v_attrs,
    },
    {
        .flags     = 0,
    },
};
iop_enum_t const tstdox__my_enum_d__e = {
    .name         = LSTR_IMMED("MyEnumD"),
    .fullname     = LSTR_IMMED("tstdox.MyEnumD"),
    .names        = tstdox__my_enum_d__names,
    .values       = tstdox__my_enum_d__values,
    .ranges       = iop__ranges__1,
    .ranges_len   = countof(iop__ranges__1) / 2,
    .enum_len     = 3,
    .flags        = 1,
    .values_attrs = tstdox__my_enum_d__e_desc_values_attrs,
};
iop_enum_t const * const tstdox__my_enum_d__ep = &tstdox__my_enum_d__e;

/* }}} */
/* Structure tstdox.MyStructA {{{ */

static iop_field_t const tstdox__my_struct_a__desc_fields[] = {
    {
        .name      = LSTR_IMMED("fieldA"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_a__t, field_a),
        .size      = fieldsizeof(tstdox__my_struct_a__t, field_a),
    },
    {
        .name      = LSTR_IMMED("fieldB"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_a__t, field_b),
        .size      = fieldsizeof(tstdox__my_struct_a__t, field_b),
    },
    {
        .name      = LSTR_IMMED("fieldC"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_a__t, field_c),
        .size      = fieldsizeof(tstdox__my_struct_a__t, field_c),
    },
};
static int const iop__ranges__3[] = {
    0, 1,
    3,
};
const iop_struct_t tstdox__my_struct_a__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructA"),
    .fields     = tstdox__my_struct_a__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(tstdox__my_struct_a__desc_fields),
    .size       = sizeof(tstdox__my_struct_a__t),
};
iop_struct_t const * const tstdox__my_struct_a__sp = &tstdox__my_struct_a__s;

/* }}} */
/* Structure tstdox.MyStructB {{{ */

static int tstdox__my_struct_b__i__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        int32_t   val = IOP_FIELD(int32_t  , ptr, j);

        if (val > 10LL) {
            if (n > 1) {
                iop_set_err("violation of constraint %s (%jd) on field %s[%d]: val=%jd",
                            "max", (int64_t)10LL, "i", j, (int64_t)val);
            } else {
                iop_set_err("violation of constraint %s (%jd) on field %s: val=%jd",
                            "max", (int64_t)10LL, "i", (int64_t)val);
            }
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const tstdox__my_struct_b__i__attrs[] = {
    {
        .type = 4,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 10LL } },
    },
};
static iop_field_attrs_t const tstdox__my_struct_b__desc_fields_attrs[] = {
    {
        .flags             = 16,
        .attrs_len         = 1,
        .check_constraints = &tstdox__my_struct_b__i__check,
        .attrs             = tstdox__my_struct_b__i__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const tstdox__my_struct_b__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_b__t, i),
        .flags     = 1,
        .size      = fieldsizeof(tstdox__my_struct_b__t, i),
    },
    {
        .name      = LSTR_IMMED("j"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_b__t, j),
        .size      = fieldsizeof(tstdox__my_struct_b__t, j),
    },
};
static int const iop__ranges__4[] = {
    0, 1,
    2,
};
const iop_struct_t tstdox__my_struct_b__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructB"),
    .fields     = tstdox__my_struct_b__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstdox__my_struct_b__desc_fields),
    .size       = sizeof(tstdox__my_struct_b__t),
    .flags      = 3,
    .fields_attrs = tstdox__my_struct_b__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_struct_b__sp = &tstdox__my_struct_b__s;

/* }}} */
/* Structure tstdox.CDataTest {{{ */

static iop_field_attrs_t const tstdox__c_data_test__desc_fields_attrs[] = {
    {
        .flags             = 4,
        .attrs_len         = 0,
    },
};
static iop_field_t const tstdox__c_data_test__desc_fields[] = {
    {
        .name      = LSTR_IMMED("sfield"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRING,
        .data_offs = offsetof(tstdox__c_data_test__t, sfield),
        .size      = fieldsizeof(tstdox__c_data_test__t, sfield),
    },
};
static int const iop__ranges__5[] = {
    0, 1,
    1,
};
const iop_struct_t tstdox__c_data_test__s = {
    .fullname   = LSTR_IMMED("tstdox.CDataTest"),
    .fields     = tstdox__c_data_test__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__c_data_test__desc_fields),
    .size       = sizeof(tstdox__c_data_test__t),
    .flags      = 1,
    .fields_attrs = tstdox__c_data_test__desc_fields_attrs,
};
iop_struct_t const * const tstdox__c_data_test__sp = &tstdox__c_data_test__s;

/* }}} */
/* Structure tstdox.MyStructAa {{{ */

static const iop_help_t tstdox__my_struct_aa__field_a__f_help = {
    .brief = LSTR_IMMED("comment for MyStructAa.fieldA"),
};
static iop_field_attr_t const tstdox__my_struct_aa__field_a__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_struct_aa__field_a__f_help } },
    },
};
static const iop_help_t tstdox__my_struct_aa__field_c__f_help = {
    .brief = LSTR_IMMED("comment for MyStructAa.fieldC"),
};
static iop_field_attr_t const tstdox__my_struct_aa__field_c__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_struct_aa__field_c__f_help } },
    },
};
static iop_field_attrs_t const tstdox__my_struct_aa__desc_fields_attrs[] = {
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_struct_aa__field_a__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_struct_aa__field_c__attrs,
    },
};
static iop_field_t const tstdox__my_struct_aa__desc_fields[] = {
    {
        .name      = LSTR_IMMED("fieldA"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_aa__t, field_a),
        .size      = fieldsizeof(tstdox__my_struct_aa__t, field_a),
    },
    {
        .name      = LSTR_IMMED("fieldB"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_aa__t, field_b),
        .size      = fieldsizeof(tstdox__my_struct_aa__t, field_b),
    },
    {
        .name      = LSTR_IMMED("fieldC"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_aa__t, field_c),
        .size      = fieldsizeof(tstdox__my_struct_aa__t, field_c),
    },
};
static const iop_help_t tstdox__my_struct_aa__s_help = {
    .brief = LSTR_IMMED("comment for MyStructAa"),
};
static const iop_struct_attr_t tstdox__my_struct_aa__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_struct_aa__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_struct_aa__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_struct_aa__s_attrs,
};
const iop_struct_t tstdox__my_struct_aa__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructAa"),
    .fields     = tstdox__my_struct_aa__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(tstdox__my_struct_aa__desc_fields),
    .size       = sizeof(tstdox__my_struct_aa__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_struct_aa__s_desc_attrs,
    .fields_attrs = tstdox__my_struct_aa__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_struct_aa__sp = &tstdox__my_struct_aa__s;

/* }}} */
/* Structure tstdox.MyStructAb {{{ */

static const iop_help_t tstdox__my_struct_ab__field_b__f_help = {
    .brief = LSTR_IMMED("comment for MyStructAb.fieldB"),
};
static iop_field_attr_t const tstdox__my_struct_ab__field_b__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_struct_ab__field_b__f_help } },
    },
};
static iop_field_attrs_t const tstdox__my_struct_ab__desc_fields_attrs[] = {
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_struct_ab__field_b__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const tstdox__my_struct_ab__desc_fields[] = {
    {
        .name      = LSTR_IMMED("fieldA"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_ab__t, field_a),
        .size      = fieldsizeof(tstdox__my_struct_ab__t, field_a),
    },
    {
        .name      = LSTR_IMMED("fieldB"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_ab__t, field_b),
        .size      = fieldsizeof(tstdox__my_struct_ab__t, field_b),
    },
    {
        .name      = LSTR_IMMED("fieldC"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_ab__t, field_c),
        .size      = fieldsizeof(tstdox__my_struct_ab__t, field_c),
    },
};
const iop_struct_t tstdox__my_struct_ab__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructAb"),
    .fields     = tstdox__my_struct_ab__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(tstdox__my_struct_ab__desc_fields),
    .size       = sizeof(tstdox__my_struct_ab__t),
    .flags      = 1,
    .fields_attrs = tstdox__my_struct_ab__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_struct_ab__sp = &tstdox__my_struct_ab__s;

/* }}} */
/* Structure tstdox.MyStructAc {{{ */

/* same as tstdox.MyStructA */

static const iop_help_t tstdox__my_struct_ac__s_help = {
    .brief = LSTR_IMMED("comment for MyStructAc"),
};
static const iop_struct_attr_t tstdox__my_struct_ac__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_struct_ac__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_struct_ac__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_struct_ac__s_attrs,
};
const iop_struct_t tstdox__my_struct_ac__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructAc"),
    .fields     = tstdox__my_struct_a__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(tstdox__my_struct_a__desc_fields),
    .size       = sizeof(tstdox__my_struct_ac__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_struct_ac__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_struct_ac__sp = &tstdox__my_struct_ac__s;

/* }}} */
/* Structure tstdox.MyStructBa {{{ */

/* same as tstdox.MyStructB */

static const iop_help_t tstdox__my_struct_ba__s_help = {
    .brief = LSTR_IMMED("comment for MyStructBa"),
};
static const iop_struct_attr_t tstdox__my_struct_ba__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_struct_ba__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_struct_ba__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_struct_ba__s_attrs,
};
const iop_struct_t tstdox__my_struct_ba__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructBa"),
    .fields     = tstdox__my_struct_b__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstdox__my_struct_b__desc_fields),
    .size       = sizeof(tstdox__my_struct_ba__t),
    .flags      = 3,
    .st_attrs   = &tstdox__my_struct_ba__s_desc_attrs,
    .fields_attrs = tstdox__my_struct_b__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_struct_ba__sp = &tstdox__my_struct_ba__s;

/* }}} */
/* Structure tstdox.MyStructBb {{{ */

static const iop_help_t tstdox__my_struct_bb__i__f_help = {
    .brief = LSTR_IMMED("comment for MyStructBb.i"),
};
static int tstdox__my_struct_bb__i__check(const void *ptr, int n)
{
    for (int j = 0; j < n; j++) {
        int32_t   val = IOP_FIELD(int32_t  , ptr, j);

        if (val > 10LL) {
            if (n > 1) {
                iop_set_err("violation of constraint %s (%jd) on field %s[%d]: val=%jd",
                            "max", (int64_t)10LL, "i", j, (int64_t)val);
            } else {
                iop_set_err("violation of constraint %s (%jd) on field %s: val=%jd",
                            "max", (int64_t)10LL, "i", (int64_t)val);
            }
            return -1;
        }
    }
    return 0;
}
static iop_field_attr_t const tstdox__my_struct_bb__i__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_struct_bb__i__f_help } },
    },
    {
        .type = 4,
        .args = (iop_field_attr_arg_t[]){ { .v.i64 = 10LL } },
    },
};
static iop_field_attrs_t const tstdox__my_struct_bb__desc_fields_attrs[] = {
    {
        .flags             = 262160,
        .attrs_len         = 2,
        .check_constraints = &tstdox__my_struct_bb__i__check,
        .attrs             = tstdox__my_struct_bb__i__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const tstdox__my_struct_bb__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_bb__t, i),
        .flags     = 1,
        .size      = fieldsizeof(tstdox__my_struct_bb__t, i),
    },
    {
        .name      = LSTR_IMMED("j"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_struct_bb__t, j),
        .size      = fieldsizeof(tstdox__my_struct_bb__t, j),
    },
};
const iop_struct_t tstdox__my_struct_bb__s = {
    .fullname   = LSTR_IMMED("tstdox.MyStructBb"),
    .fields     = tstdox__my_struct_bb__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstdox__my_struct_bb__desc_fields),
    .size       = sizeof(tstdox__my_struct_bb__t),
    .flags      = 3,
    .fields_attrs = tstdox__my_struct_bb__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_struct_bb__sp = &tstdox__my_struct_bb__s;

/* }}} */
/* Structure tstdox.SortField {{{ */

static const iop_help_t tstdox__sort_field__pos__f_help = {
    .brief = LSTR_IMMED("Position of the field to use in the \134ref Extract::fields"),
};
static iop_field_attr_t const tstdox__sort_field__pos__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__sort_field__pos__f_help } },
    },
};
static iop_field_attrs_t const tstdox__sort_field__desc_fields_attrs[] = {
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__sort_field__pos__attrs,
    },
};
static iop_field_t const tstdox__sort_field__desc_fields[] = {
    {
        .name      = LSTR_IMMED("pos"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_U32,
        .data_offs = offsetof(tstdox__sort_field__t, pos),
        .size      = fieldsizeof(tstdox__sort_field__t, pos),
    },
};
static const iop_help_t tstdox__sort_field__s_help = {
    .brief = LSTR_IMMED("Specify a sorting condition on a field"),
};
static const iop_struct_attr_t tstdox__sort_field__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__sort_field__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__sort_field__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__sort_field__s_attrs,
};
const iop_struct_t tstdox__sort_field__s = {
    .fullname   = LSTR_IMMED("tstdox.SortField"),
    .fields     = tstdox__sort_field__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__sort_field__desc_fields),
    .size       = sizeof(tstdox__sort_field__t),
    .flags      = 1,
    .st_attrs   = &tstdox__sort_field__s_desc_attrs,
    .fields_attrs = tstdox__sort_field__desc_fields_attrs,
};
iop_struct_t const * const tstdox__sort_field__sp = &tstdox__sort_field__s;

/* }}} */
/* Class tstdox.MyClassBase {{{ */

static iop_field_t const tstdox__my_class_base__desc_fields[] = {
};

static const iop_help_t tstdox__my_class_base__static_field_0__sf_help = {
    .brief = LSTR_IMMED("comment for val of MyClassBase"),
};
static const iop_field_attr_t tstdox__my_class_base__static_field_0__sf_attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_class_base__static_field_0__sf_help } },
    },
};
static const iop_field_attrs_t tstdox__my_class_base__static_field_0__sf_desc_attrs = {
    .flags     = 262144,
    .attrs_len = 1,
    .attrs     = tstdox__my_class_base__static_field_0__sf_attrs,
};
static const iop_static_field_t tstdox__my_class_base__static_field_0 = {
    .name  = LSTR_IMMED("val"),
    .value = { .i = 10 },
    .type  = IOP_T_I64,
    .attrs = &tstdox__my_class_base__static_field_0__sf_desc_attrs,
};
static const iop_static_field_t *tstdox__my_class_base__static_fields[] = {
    &tstdox__my_class_base__static_field_0,
};

static int const iop__ranges__6[] = {
    0,
};
static const iop_class_attrs_t tstdox__my_class_base__class_s = {
    .static_fields     = tstdox__my_class_base__static_fields,
    .static_fields_len = 1,
    .is_abstract       = true,
    .class_id          = 0,
};
const iop_struct_t tstdox__my_class_base__s = {
    .fullname   = LSTR_IMMED("tstdox.MyClassBase"),
    .fields     = tstdox__my_class_base__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(tstdox__my_class_base__desc_fields),
    .size       = sizeof(tstdox__my_class_base__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &tstdox__my_class_base__class_s,
    }
};
iop_struct_t const * const tstdox__my_class_base__sp = &tstdox__my_class_base__s;

/* }}} */
/* Class tstdox.MyClassA {{{ */

static iop_field_t const tstdox__my_class_a__desc_fields[] = {
};

static const iop_static_field_t tstdox__my_class_a__static_field_0 = {
    .name  = LSTR_IMMED("name"),
    .value = { .s = LSTR_IMMED("MyClassA") },
    .type  = IOP_T_STRING,
};
static const iop_static_field_t tstdox__my_class_a__static_field_1 = {
    .name  = LSTR_IMMED("val"),
    .value = { .i = 100 },
    .type  = IOP_T_I64,
};
static const iop_static_field_t *tstdox__my_class_a__static_fields[] = {
    &tstdox__my_class_a__static_field_0,
    &tstdox__my_class_a__static_field_1,
};

static const iop_class_attrs_t tstdox__my_class_a__class_s = {
    .parent            = &tstdox__my_class_base__s,
    .static_fields     = tstdox__my_class_a__static_fields,
    .static_fields_len = 2,
    .class_id          = 1,
};
const iop_struct_t tstdox__my_class_a__s = {
    .fullname   = LSTR_IMMED("tstdox.MyClassA"),
    .fields     = tstdox__my_class_a__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(tstdox__my_class_a__desc_fields),
    .size       = sizeof(tstdox__my_class_a__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &tstdox__my_class_a__class_s,
    }
};
iop_struct_t const * const tstdox__my_class_a__sp = &tstdox__my_class_a__s;

/* }}} */
/* Class tstdox.MyClass1 {{{ */

static iop_field_t const tstdox__my_class1__desc_fields[] = {
};
static const iop_help_t tstdox__my_class1__s_help = {
    .brief = LSTR_IMMED("no comment in static fields"),
};
static const iop_struct_attr_t tstdox__my_class1__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_class1__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_class1__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_class1__s_attrs,
};
static const iop_class_attrs_t tstdox__my_class1__class_s = {
    .is_abstract       = true,
    .class_id          = 1,
};
const iop_struct_t tstdox__my_class1__s = {
    .fullname   = LSTR_IMMED("tstdox.MyClass1"),
    .fields     = tstdox__my_class1__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(tstdox__my_class1__desc_fields),
    .size       = sizeof(tstdox__my_class1__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = &tstdox__my_class1__s_desc_attrs,
    .fields_attrs = NULL,
    {
        .class_attrs  = &tstdox__my_class1__class_s,
    }
};
iop_struct_t const * const tstdox__my_class1__sp = &tstdox__my_class1__s;

/* }}} */
/* Class tstdox.MyClass2 {{{ */

static iop_field_t const tstdox__my_class2__desc_fields[] = {
};

static const iop_static_field_t tstdox__my_class2__static_field_0 = {
    .name  = LSTR_IMMED("fieldA"),
    .value = { .i = 1 },
    .type  = IOP_T_I64,
};
static const iop_static_field_t *tstdox__my_class2__static_fields[] = {
    &tstdox__my_class2__static_field_0,
};

static const iop_class_attrs_t tstdox__my_class2__class_s = {
    .parent            = &tstdox__my_class1__s,
    .static_fields     = tstdox__my_class2__static_fields,
    .static_fields_len = 1,
    .class_id          = 2,
};
const iop_struct_t tstdox__my_class2__s = {
    .fullname   = LSTR_IMMED("tstdox.MyClass2"),
    .fields     = tstdox__my_class2__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(tstdox__my_class2__desc_fields),
    .size       = sizeof(tstdox__my_class2__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &tstdox__my_class2__class_s,
    }
};
iop_struct_t const * const tstdox__my_class2__sp = &tstdox__my_class2__s;

/* }}} */
/* Interface tstdox.MyIfaceA {{{ */
/* Structure tstdox.MyIfaceA.funAArgs {{{ */

static const iop_help_t tstdox__my_iface_a__fun_a_args__a_param__f_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.in.aParam"),
    .details = LSTR_IMMED("comment for aParam of funA.in\012                      it continues here"),
};
static iop_field_attr_t const tstdox__my_iface_a__fun_a_args__a_param__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_args__a_param__f_help } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_a_args__b__f_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.in.b"),
    .details = LSTR_IMMED("comment for b of funA.in"),
};
static iop_field_attr_t const tstdox__my_iface_a__fun_a_args__b__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_args__b__f_help } },
    },
};
static iop_field_attrs_t const tstdox__my_iface_a__fun_a_args__desc_fields_attrs[] = {
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_a_args__a_param__attrs,
    },
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_a_args__b__attrs,
    },
};
static iop_field_t const tstdox__my_iface_a__fun_a_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("aParam"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_a__fun_a_args__t, a_param),
        .size      = fieldsizeof(tstdox__my_iface_a__fun_a_args__t, a_param),
    },
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(tstdox__my_iface_a__fun_a_args__t, b),
        .size      = sizeof(tstdox__my_struct_aa__t),
        .u1        = { .st_desc = &tstdox__my_struct_aa__s },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_a_args__s_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.in"),
    .details = LSTR_NULL,
    .example = LSTR_IMMED("{\042aParam\042:1,\042b\042:{\042fieldA\042:11,\042fieldB\042:12,\042fieldC\042:13}}"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_a_args__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_args__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_a_args__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_a_args__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_a_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funAArgs"),
    .fields     = tstdox__my_iface_a__fun_a_args__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_a_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_a_args__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_a_args__s_desc_attrs,
    .fields_attrs = tstdox__my_iface_a__fun_a_args__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_a_args__sp = &tstdox__my_iface_a__fun_a_args__s;

/* }}} */
/* Structure tstdox.MyIfaceA.funARes {{{ */

static const iop_help_t tstdox__my_iface_a__fun_a_res__c__f_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.out.c"),
    .details = LSTR_IMMED("comment for c of funA.out"),
};
static iop_field_attr_t const tstdox__my_iface_a__fun_a_res__c__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_res__c__f_help } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_a_res__d__f_help = {
    .details = LSTR_IMMED("comment for \134ref d of funA.out\0122nd paragraph for \134p d of funA.out"),
};
static iop_field_attr_t const tstdox__my_iface_a__fun_a_res__d__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_res__d__f_help } },
    },
};
static iop_field_attrs_t const tstdox__my_iface_a__fun_a_res__desc_fields_attrs[] = {
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_a_res__c__attrs,
    },
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_a_res__d__attrs,
    },
};
static iop_field_t const tstdox__my_iface_a__fun_a_res__desc_fields[] = {
    {
        .name      = LSTR_IMMED("c"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(tstdox__my_iface_a__fun_a_res__t, c),
        .size      = sizeof(tstdox__my_struct_a__t),
        .u1        = { .st_desc = &tstdox__my_struct_a__s },
    },
    {
        .name      = LSTR_IMMED("d"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_a__fun_a_res__t, d),
        .size      = fieldsizeof(tstdox__my_iface_a__fun_a_res__t, d),
    },
};
static const iop_help_t tstdox__my_iface_a__fun_a_res__s_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.out"),
    .details = LSTR_NULL,
    .example = LSTR_IMMED("{\042c\042:{\042fieldA\042:11,\042fieldB\042:12,\042fieldC\042:13},\042d\042:4}"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_a_res__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a_res__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_a_res__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_a_res__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_a_res__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funARes"),
    .fields     = tstdox__my_iface_a__fun_a_res__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_a_res__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_a_res__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_a_res__s_desc_attrs,
    .fields_attrs = tstdox__my_iface_a__fun_a_res__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_a_res__sp = &tstdox__my_iface_a__fun_a_res__s;

/* }}} */
#define tstdox__my_iface_a__fun_a_exn__desc_fields  tstdox__my_struct_ac__desc_fields
#define tstdox__my_iface_a__fun_a_exn__s_ranges     tstdox__my_struct_ac__s_ranges
#define tstdox__my_iface_a__fun_a_exn__s            tstdox__my_struct_ac__s
/* Structure tstdox.MyIfaceA.funAaArgs {{{ */

static iop_field_t const tstdox__my_iface_a__fun_aa_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("a"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_a__fun_aa_args__t, a),
        .size      = fieldsizeof(tstdox__my_iface_a__fun_aa_args__t, a),
    },
};
static const iop_help_t tstdox__my_iface_a__fun_aa_args__s_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funAa.in"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_aa_args__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_aa_args__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_aa_args__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_aa_args__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_aa_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funAaArgs"),
    .fields     = tstdox__my_iface_a__fun_aa_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_aa_args__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_aa_args__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_aa_args__sp = &tstdox__my_iface_a__fun_aa_args__s;

/* }}} */
/* Structure tstdox.MyIfaceA.funAaRes {{{ */

static iop_field_t const tstdox__my_iface_a__fun_aa_res__desc_fields[] = {
    {
        .name      = LSTR_IMMED("b"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_a__fun_aa_res__t, b),
        .size      = fieldsizeof(tstdox__my_iface_a__fun_aa_res__t, b),
    },
};
static const iop_help_t tstdox__my_iface_a__fun_aa_res__s_help = {
    .example = LSTR_IMMED("{\042b\042:3}"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_aa_res__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_aa_res__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_aa_res__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_aa_res__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_aa_res__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funAaRes"),
    .fields     = tstdox__my_iface_a__fun_aa_res__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_res__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_aa_res__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_aa_res__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_aa_res__sp = &tstdox__my_iface_a__fun_aa_res__s;

/* }}} */
/* Structure tstdox.MyIfaceA.funBArgs {{{ */

/* same as tstdox.MyIfaceA.funAaArgs */

static const iop_help_t tstdox__my_iface_a__fun_b_args__s_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funB.in"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_b_args__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_b_args__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_b_args__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_b_args__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_b_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funBArgs"),
    .fields     = tstdox__my_iface_a__fun_aa_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_b_args__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_b_args__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_b_args__sp = &tstdox__my_iface_a__fun_b_args__s;

/* }}} */
const iop_struct_t tstdox__my_iface_a__fun_bal1_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funBal1Args"),
    .fields     = tstdox__my_iface_a__fun_aa_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_b_args__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_b_args__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_bal1_args__sp = &tstdox__my_iface_a__fun_bal1_args__s;

/* }}} */
const iop_struct_t tstdox__my_iface_a__fun_bal2_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funBal2Args"),
    .fields     = tstdox__my_iface_a__fun_aa_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_b_args__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_b_args__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_bal2_args__sp = &tstdox__my_iface_a__fun_bal2_args__s;

/* }}} */
#define tstdox__my_iface_a__fun_b_res__desc_fields  tstdox__my_struct_a__desc_fields
#define tstdox__my_iface_a__fun_b_res__s_ranges     tstdox__my_struct_a__s_ranges
#define tstdox__my_iface_a__fun_b_res__s            tstdox__my_struct_a__s
#define tstdox__my_iface_a__fun_bal1_res__s            tstdox__my_struct_a__s
#define tstdox__my_iface_a__fun_bal2_res__s            tstdox__my_struct_a__s
#define tstdox__my_iface_a__fun_c_args__desc_fields  tstdox__my_struct_a__desc_fields
#define tstdox__my_iface_a__fun_c_args__s_ranges     tstdox__my_struct_a__s_ranges
#define tstdox__my_iface_a__fun_c_args__s            tstdox__my_struct_a__s
/* Structure tstdox.MyIfaceA.funCRes {{{ */

/* same as tstdox.MyIfaceA.funAaRes */

const iop_struct_t tstdox__my_iface_a__fun_c_res__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funCRes"),
    .fields     = tstdox__my_iface_a__fun_aa_res__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_res__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_c_res__t),
    .flags      = 1,
};
iop_struct_t const * const tstdox__my_iface_a__fun_c_res__sp = &tstdox__my_iface_a__fun_c_res__s;

/* }}} */
/* Structure tstdox.MyIfaceA.funDRes {{{ */

/* same as tstdox.MyIfaceA.funAaRes */

static const iop_help_t tstdox__my_iface_a__fun_d_res__s_help = {
    .brief = LSTR_IMMED("front comment... and back comment for res of funD"),
};
static const iop_struct_attr_t tstdox__my_iface_a__fun_d_res__s_attrs[] = {
    {
        .type = 6,
        .args = (iop_struct_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_d_res__s_help } },
    },
};
static const iop_struct_attrs_t tstdox__my_iface_a__fun_d_res__s_desc_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__fun_d_res__s_attrs,
};
const iop_struct_t tstdox__my_iface_a__fun_d_res__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funDRes"),
    .fields     = tstdox__my_iface_a__fun_aa_res__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_aa_res__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_d_res__t),
    .flags      = 1,
    .st_attrs   = &tstdox__my_iface_a__fun_d_res__s_desc_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_d_res__sp = &tstdox__my_iface_a__fun_d_res__s;

/* }}} */
/* Structure tstdox.MyIfaceA.funEArgs {{{ */

static const iop_help_t tstdox__my_iface_a__fun_e_args__a__f_help = {
    .details = LSTR_IMMED("It is a \134p comment for \134ref a"),
};
static iop_field_attr_t const tstdox__my_iface_a__fun_e_args__a__attrs[] = {
    {
        .type = 18,
        .args = (iop_field_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_e_args__a__f_help } },
    },
};
static iop_field_attrs_t const tstdox__my_iface_a__fun_e_args__desc_fields_attrs[] = {
    {
        .flags             = 262144,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_e_args__a__attrs,
    },
};
static iop_field_t const tstdox__my_iface_a__fun_e_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("a"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_a__fun_e_args__t, a),
        .size      = fieldsizeof(tstdox__my_iface_a__fun_e_args__t, a),
    },
};
const iop_struct_t tstdox__my_iface_a__fun_e_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funEArgs"),
    .fields     = tstdox__my_iface_a__fun_e_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_e_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_e_args__t),
    .flags      = 1,
    .fields_attrs = tstdox__my_iface_a__fun_e_args__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_e_args__sp = &tstdox__my_iface_a__fun_e_args__s;

/* }}} */
const iop_struct_t tstdox__my_iface_a__fun_e1_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funE1Args"),
    .fields     = tstdox__my_iface_a__fun_e_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_e_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_e_args__t),
    .flags      = 1,
    .fields_attrs = tstdox__my_iface_a__fun_e_args__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_e1_args__sp = &tstdox__my_iface_a__fun_e1_args__s;

/* }}} */
const iop_struct_t tstdox__my_iface_a__fun_e2_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA.funE2Args"),
    .fields     = tstdox__my_iface_a__fun_e_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_a__fun_e_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_a__fun_e_args__t),
    .flags      = 1,
    .fields_attrs = tstdox__my_iface_a__fun_e_args__desc_fields_attrs,
};
iop_struct_t const * const tstdox__my_iface_a__fun_e2_args__sp = &tstdox__my_iface_a__fun_e2_args__s;

/* }}} */
static iop_rpc_t const tstdox__my_iface_a__if_funs[] = {
    {
        .name      = LSTR_IMMED("funA"),
        .tag       = 1,
        .args      = &tstdox__my_iface_a__fun_a_args__s,
        .result    = &tstdox__my_iface_a__fun_a_res__s,
        .exn       = &tstdox__my_iface_a__fun_a_exn__s,
    },
    {
        .name      = LSTR_IMMED("funAa"),
        .tag       = 2,
        .args      = &tstdox__my_iface_a__fun_aa_args__s,
        .result    = &tstdox__my_iface_a__fun_aa_res__s,
        .exn       = &iop__void__s,
    },
    {
        .name      = LSTR_IMMED("funB"),
        .tag       = 3,
        .args      = &tstdox__my_iface_a__fun_b_args__s,
        .result    = &tstdox__my_iface_a__fun_b_res__s,
        .exn       = &iop__void__s,
        .flags     = 2,
    },
    {
        .name      = LSTR_IMMED("funBal1"),
        .tag       = 3,
        .args      = &tstdox__my_iface_a__fun_bal1_args__s,
        .result    = &tstdox__my_iface_a__fun_bal1_res__s,
        .exn       = &iop__void__s,
        .flags     = 1,
    },
    {
        .name      = LSTR_IMMED("funBal2"),
        .tag       = 3,
        .args      = &tstdox__my_iface_a__fun_bal2_args__s,
        .result    = &tstdox__my_iface_a__fun_bal2_res__s,
        .exn       = &iop__void__s,
        .flags     = 1,
    },
    {
        .name      = LSTR_IMMED("funC"),
        .tag       = 4,
        .args      = &tstdox__my_iface_a__fun_c_args__s,
        .result    = &tstdox__my_iface_a__fun_c_res__s,
        .exn       = &iop__void__s,
    },
    {
        .name      = LSTR_IMMED("funD"),
        .tag       = 5,
        .args      = &iop__void__s,
        .result    = &tstdox__my_iface_a__fun_d_res__s,
        .exn       = &iop__void__s,
    },
    {
        .name      = LSTR_IMMED("funE"),
        .tag       = 6,
        .args      = &tstdox__my_iface_a__fun_e_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .flags     = 2,
    },
    {
        .name      = LSTR_IMMED("funE1"),
        .tag       = 6,
        .args      = &tstdox__my_iface_a__fun_e1_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .flags     = 1,
    },
    {
        .name      = LSTR_IMMED("funE2"),
        .tag       = 6,
        .args      = &tstdox__my_iface_a__fun_e2_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .flags     = 1,
    },
};
static const iop_help_t tstdox__my_iface_a__fun_a__rpc_help = {
    .brief = LSTR_IMMED("comment for funA of MyIfaceA"),
    .details = LSTR_IMMED("detailed description for funA of MyIfaceA"),
    .warning = LSTR_IMMED("warning for funA of MyIfaceA"),
};
static const iop_help_t tstdox__my_iface_a__fun_a__rpc_exn_help = {
    .brief = LSTR_IMMED("local comment for MyIfaceA.funA.throw"),
    .details = LSTR_IMMED("comment for funA.throw"),
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_a__attrs[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a__rpc_help } },
    },
    {
        .type = 12,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_a__rpc_exn_help } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_b__rpc_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funB"),
};
static const iop_help_t tstdox__my_iface_a__fun_b__rpc_res_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funB.out"),
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_b__attrs_na[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_b__rpc_help } },
    },
    {
        .type = 11,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_b__rpc_res_help } },
    },
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_b__attrs[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_b__rpc_help } },
    },
    {
        .type = 11,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_b__rpc_res_help } },
    },
    {
        .type = 0,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = (void*)&tstdox__my_iface_a__if_funs[3] } },
    },
    {
        .type = 0,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = (void*)&tstdox__my_iface_a__if_funs[4] } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_c__rpc_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funC"),
};
static const iop_help_t tstdox__my_iface_a__fun_c__rpc_arg_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA.funC.in"),
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_c__attrs[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_c__rpc_help } },
    },
    {
        .type = 10,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_c__rpc_arg_help } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_d__rpc_help = {
    .brief = LSTR_IMMED("front comment... and back comment for funD"),
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_d__attrs[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_d__rpc_help } },
    },
};
static const iop_help_t tstdox__my_iface_a__fun_e__rpc_help = {
    .brief = LSTR_IMMED("Comment for funE"),
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_e__attrs_na[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_e__rpc_help } },
    },
};
static iop_rpc_attr_t const tstdox__my_iface_a__fun_e__attrs[] = {
    {
        .type = 9,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__fun_e__rpc_help } },
    },
    {
        .type = 0,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = (void*)&tstdox__my_iface_a__if_funs[8] } },
    },
    {
        .type = 0,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = (void*)&tstdox__my_iface_a__if_funs[9] } },
    },
};
static iop_rpc_attrs_t const tstdox__my_iface_a__rpc_desc_attrs[] = {
    {
        .flags             = 4608,
        .attrs_len         = 2,
        .attrs             = tstdox__my_iface_a__fun_a__attrs,
    },
    {
        .flags             = 0,
    },
    {
        .flags             = 2561,
        .attrs_len         = 4,
        .attrs             = tstdox__my_iface_a__fun_b__attrs,
    },
    {
        .flags             = 2560,
        .attrs_len         = 2,
        .attrs             = tstdox__my_iface_a__fun_b__attrs_na,
    },
    {
        .flags             = 2560,
        .attrs_len         = 2,
        .attrs             = tstdox__my_iface_a__fun_b__attrs_na,
    },
    {
        .flags             = 1536,
        .attrs_len         = 2,
        .attrs             = tstdox__my_iface_a__fun_c__attrs,
    },
    {
        .flags             = 512,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_d__attrs,
    },
    {
        .flags             = 513,
        .attrs_len         = 3,
        .attrs             = tstdox__my_iface_a__fun_e__attrs,
    },
    {
        .flags             = 512,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_e__attrs_na,
    },
    {
        .flags             = 512,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_a__fun_e__attrs_na,
    },
};
static const iop_help_t tstdox__my_iface_a__if_help = {
    .brief = LSTR_IMMED("comment for MyIfaceA"),
};
static const iop_iface_attr_t tstdox__my_iface_a__if_attrs[] = {
    {
        .type = 6,
        .args = (iop_iface_attr_arg_t[]){ { .v.p = &tstdox__my_iface_a__if_help } },
    },
};
static const iop_iface_attrs_t tstdox__my_iface_a__desc_if_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_a__if_attrs,
};
const iop_iface_t tstdox__my_iface_a__if = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceA"),
    .funs       = tstdox__my_iface_a__if_funs,
    .funs_len   = countof(tstdox__my_iface_a__if_funs),
    .flags      = 3,
    .rpc_attrs  = tstdox__my_iface_a__rpc_desc_attrs,
    .iface_attrs  = &tstdox__my_iface_a__desc_if_attrs,
};
const iop_iface_t * const tstdox__my_iface_a__ifp = &tstdox__my_iface_a__if;

/* }}} */
/* Interface tstdox.MyIfaceB {{{ */
/* Structure tstdox.MyIfaceB.funAArgs {{{ */

static iop_field_t const tstdox__my_iface_b__fun_a_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_b__fun_a_args__t, i),
        .size      = fieldsizeof(tstdox__my_iface_b__fun_a_args__t, i),
    },
};
const iop_struct_t tstdox__my_iface_b__fun_a_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceB.funAArgs"),
    .fields     = tstdox__my_iface_b__fun_a_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_a_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_b__fun_a_args__t),
};
iop_struct_t const * const tstdox__my_iface_b__fun_a_args__sp = &tstdox__my_iface_b__fun_a_args__s;

/* }}} */
/* Structure tstdox.MyIfaceB.funBArgs {{{ */

static iop_field_t const tstdox__my_iface_b__fun_b_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("j"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstdox__my_iface_b__fun_b_args__t, j),
        .size      = fieldsizeof(tstdox__my_iface_b__fun_b_args__t, j),
    },
};
const iop_struct_t tstdox__my_iface_b__fun_b_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceB.funBArgs"),
    .fields     = tstdox__my_iface_b__fun_b_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_b_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_b__fun_b_args__t),
};
iop_struct_t const * const tstdox__my_iface_b__fun_b_args__sp = &tstdox__my_iface_b__fun_b_args__s;

/* }}} */
static iop_rpc_t const tstdox__my_iface_b__if_funs[] = {
    {
        .name      = LSTR_IMMED("funA"),
        .tag       = 1,
        .args      = &tstdox__my_iface_b__fun_a_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
    {
        .name      = LSTR_IMMED("funB"),
        .tag       = 2,
        .args      = &tstdox__my_iface_b__fun_b_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
};
const iop_iface_t tstdox__my_iface_b__if = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceB"),
    .funs       = tstdox__my_iface_b__if_funs,
    .funs_len   = countof(tstdox__my_iface_b__if_funs),
};
const iop_iface_t * const tstdox__my_iface_b__ifp = &tstdox__my_iface_b__if;

/* }}} */
/* Interface tstdox.MyIfaceC {{{ */
/* Structure tstdox.MyIfaceC.funAArgs {{{ */

/* same as tstdox.MyIfaceB.funAArgs */

const iop_struct_t tstdox__my_iface_c__fun_a_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceC.funAArgs"),
    .fields     = tstdox__my_iface_b__fun_a_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_a_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_c__fun_a_args__t),
};
iop_struct_t const * const tstdox__my_iface_c__fun_a_args__sp = &tstdox__my_iface_c__fun_a_args__s;

/* }}} */
const iop_struct_t tstdox__my_iface_c__fun_a2_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceC.funA2Args"),
    .fields     = tstdox__my_iface_b__fun_a_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_a_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_c__fun_a_args__t),
};
iop_struct_t const * const tstdox__my_iface_c__fun_a2_args__sp = &tstdox__my_iface_c__fun_a2_args__s;

/* }}} */
/* Structure tstdox.MyIfaceC.funBArgs {{{ */

/* same as tstdox.MyIfaceB.funBArgs */

const iop_struct_t tstdox__my_iface_c__fun_b_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceC.funBArgs"),
    .fields     = tstdox__my_iface_b__fun_b_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_b_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_c__fun_b_args__t),
};
iop_struct_t const * const tstdox__my_iface_c__fun_b_args__sp = &tstdox__my_iface_c__fun_b_args__s;

/* }}} */
static iop_rpc_t const tstdox__my_iface_c__if_funs[] = {
    {
        .name      = LSTR_IMMED("funA"),
        .tag       = 1,
        .args      = &tstdox__my_iface_c__fun_a_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .flags     = 2,
    },
    {
        .name      = LSTR_IMMED("funA2"),
        .tag       = 1,
        .args      = &tstdox__my_iface_c__fun_a2_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .flags     = 1,
    },
    {
        .name      = LSTR_IMMED("funB"),
        .tag       = 2,
        .args      = &tstdox__my_iface_c__fun_b_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
};
static iop_rpc_attr_t const tstdox__my_iface_c__fun_a__attrs[] = {
    {
        .type = 0,
        .args = (iop_rpc_attr_arg_t[]){ { .v.p = (void*)&tstdox__my_iface_c__if_funs[1] } },
    },
};
static iop_rpc_attrs_t const tstdox__my_iface_c__rpc_desc_attrs[] = {
    {
        .flags             = 1,
        .attrs_len         = 1,
        .attrs             = tstdox__my_iface_c__fun_a__attrs,
    },
    {
        .flags             = 0,
    },
    {
        .flags             = 0,
    },
};
const iop_iface_t tstdox__my_iface_c__if = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceC"),
    .funs       = tstdox__my_iface_c__if_funs,
    .funs_len   = countof(tstdox__my_iface_c__if_funs),
    .flags      = 1,
    .rpc_attrs  = tstdox__my_iface_c__rpc_desc_attrs,
};
const iop_iface_t * const tstdox__my_iface_c__ifp = &tstdox__my_iface_c__if;

/* }}} */
/* Interface tstdox.MyIfaceD {{{ */
/* Structure tstdox.MyIfaceD.funAArgs {{{ */

/* same as tstdox.MyIfaceB.funAArgs */

const iop_struct_t tstdox__my_iface_d__fun_a_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceD.funAArgs"),
    .fields     = tstdox__my_iface_b__fun_a_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_a_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_d__fun_a_args__t),
};
iop_struct_t const * const tstdox__my_iface_d__fun_a_args__sp = &tstdox__my_iface_d__fun_a_args__s;

/* }}} */
/* Structure tstdox.MyIfaceD.funBArgs {{{ */

/* same as tstdox.MyIfaceB.funBArgs */

const iop_struct_t tstdox__my_iface_d__fun_b_args__s = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceD.funBArgs"),
    .fields     = tstdox__my_iface_b__fun_b_args__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstdox__my_iface_b__fun_b_args__desc_fields),
    .size       = sizeof(tstdox__my_iface_d__fun_b_args__t),
};
iop_struct_t const * const tstdox__my_iface_d__fun_b_args__sp = &tstdox__my_iface_d__fun_b_args__s;

/* }}} */
static iop_rpc_t const tstdox__my_iface_d__if_funs[] = {
    {
        .name      = LSTR_IMMED("funA"),
        .tag       = 1,
        .args      = &tstdox__my_iface_d__fun_a_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
    {
        .name      = LSTR_IMMED("funB"),
        .tag       = 2,
        .args      = &tstdox__my_iface_d__fun_b_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
};
static const iop_help_t tstdox__my_iface_d__if_help = {
    .brief = LSTR_IMMED("comment for MyIfaceD"),
};
static const iop_iface_attr_t tstdox__my_iface_d__if_attrs[] = {
    {
        .type = 6,
        .args = (iop_iface_attr_arg_t[]){ { .v.p = &tstdox__my_iface_d__if_help } },
    },
};
static const iop_iface_attrs_t tstdox__my_iface_d__desc_if_attrs = {
    .flags     = 64,
    .attrs_len = 1,
    .attrs     = tstdox__my_iface_d__if_attrs,
};
const iop_iface_t tstdox__my_iface_d__if = {
    .fullname   = LSTR_IMMED("tstdox.MyIfaceD"),
    .funs       = tstdox__my_iface_d__if_funs,
    .funs_len   = countof(tstdox__my_iface_d__if_funs),
    .flags      = 2,
    .iface_attrs  = &tstdox__my_iface_d__desc_if_attrs,
};
const iop_iface_t * const tstdox__my_iface_d__ifp = &tstdox__my_iface_d__if;

/* }}} */
/* Module tstdox.MyModuleA {{{ */

static iop_iface_alias_t const tstdox__my_module_a__aliases[] = {
    {
        .name  = LSTR_IMMED("ifaceA"),
        .iface = &tstdox__my_iface_a__if,
        .tag   = 1,
    },
    {
        .name  = LSTR_IMMED("ifaceB"),
        .iface = &tstdox__my_iface_b__if,
        .tag   = 2,
    },
    {
        .name  = LSTR_IMMED("ifaceC"),
        .iface = &tstdox__my_iface_c__if,
        .tag   = 3,
    },
};
static const iop_help_t tstdox__my_module_a__iface_a__m_if_help = {
    .brief = LSTR_IMMED("comment for MyModuleA.ifaceA"),
};
static const iop_mod_iface_attr_t tstdox__my_module_a__iface_a__m_if_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_iface_attr_arg_t[]){ { .v.p = &tstdox__my_module_a__iface_a__m_if_help } },
    },
};
static const iop_help_t tstdox__my_module_a__iface_c__m_if_help = {
    .brief = LSTR_IMMED("comment for MyModuleA.ifaceC"),
};
static const iop_mod_iface_attr_t tstdox__my_module_a__iface_c__m_if_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_iface_attr_arg_t[]){ { .v.p = &tstdox__my_module_a__iface_c__m_if_help } },
    },
};
static const iop_mod_iface_attrs_t tstdox__my_module_a__m_desc_if_attrs[] = {
    {
        .flags     = 2,
        .attrs_len = 1,
        .attrs     = tstdox__my_module_a__iface_a__m_if_attrs,
    },
    {
        .flags     = 0,
    },
    {
        .flags     = 2,
        .attrs_len = 1,
        .attrs     = tstdox__my_module_a__iface_c__m_if_attrs,
    },
};
iop_mod_t const tstdox__my_module_a__mod = {
    .fullname   = LSTR_IMMED("tstdox.MyModuleA"),
    .ifaces     = tstdox__my_module_a__aliases,
    .ifaces_len = countof(tstdox__my_module_a__aliases),
    .flags      = 1,
    .ifaces_attrs = tstdox__my_module_a__m_desc_if_attrs,
};
iop_mod_t const * const tstdox__my_module_a__modp = &tstdox__my_module_a__mod;

/* }}} */
/* Module tstdox.MyModuleB {{{ */

static iop_iface_alias_t const tstdox__my_module_b__aliases[] = {
    {
        .name  = LSTR_IMMED("ifaceA"),
        .iface = &tstdox__my_iface_a__if,
        .tag   = 1,
    },
    {
        .name  = LSTR_IMMED("ifaceB"),
        .iface = &tstdox__my_iface_b__if,
        .tag   = 2,
    },
    {
        .name  = LSTR_IMMED("ifaceC"),
        .iface = &tstdox__my_iface_c__if,
        .tag   = 3,
    },
};
static const iop_help_t tstdox__my_module_b__m_help = {
    .brief = LSTR_IMMED("comment for MyModuleB"),
};
static const iop_mod_attr_t tstdox__my_module_b__m_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_attr_arg_t[]){ { .v.p = &tstdox__my_module_b__m_help } },
    },
};
static const iop_mod_attrs_t tstdox__my_module_b__m_desc_attrs = {
    .flags     = 2,
    .attrs_len = 1,
    .attrs     = tstdox__my_module_b__m_attrs,
};
iop_mod_t const tstdox__my_module_b__mod = {
    .fullname   = LSTR_IMMED("tstdox.MyModuleB"),
    .ifaces     = tstdox__my_module_b__aliases,
    .ifaces_len = countof(tstdox__my_module_b__aliases),
    .flags      = 1,
    .mod_attrs  = &tstdox__my_module_b__m_desc_attrs,
};
iop_mod_t const * const tstdox__my_module_b__modp = &tstdox__my_module_b__mod;

/* }}} */
/* Module tstdox.MyModuleC {{{ */

static iop_iface_alias_t const tstdox__my_module_c__aliases[] = {
    {
        .name  = LSTR_IMMED("ifaceA"),
        .iface = &tstdox__my_iface_a__if,
        .tag   = 1,
    },
    {
        .name  = LSTR_IMMED("ifaceB"),
        .iface = &tstdox__my_iface_b__if,
        .tag   = 2,
    },
    {
        .name  = LSTR_IMMED("ifaceC"),
        .iface = &tstdox__my_iface_c__if,
        .tag   = 3,
    },
};
static const iop_help_t tstdox__my_module_c__iface_a__m_if_help = {
    .brief = LSTR_IMMED("comment for MyModuleC.ifaceA"),
};
static const iop_mod_iface_attr_t tstdox__my_module_c__iface_a__m_if_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_iface_attr_arg_t[]){ { .v.p = &tstdox__my_module_c__iface_a__m_if_help } },
    },
};
static const iop_help_t tstdox__my_module_c__iface_c__m_if_help = {
    .brief = LSTR_IMMED("comment for MyModuleC.ifaceC"),
};
static const iop_mod_iface_attr_t tstdox__my_module_c__iface_c__m_if_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_iface_attr_arg_t[]){ { .v.p = &tstdox__my_module_c__iface_c__m_if_help } },
    },
};
static const iop_mod_iface_attrs_t tstdox__my_module_c__m_desc_if_attrs[] = {
    {
        .flags     = 2,
        .attrs_len = 1,
        .attrs     = tstdox__my_module_c__iface_a__m_if_attrs,
    },
    {
        .flags     = 0,
    },
    {
        .flags     = 2,
        .attrs_len = 1,
        .attrs     = tstdox__my_module_c__iface_c__m_if_attrs,
    },
};
static const iop_help_t tstdox__my_module_c__m_help = {
    .brief = LSTR_IMMED("comment for MyModuleC"),
};
static const iop_mod_attr_t tstdox__my_module_c__m_attrs[] = {
    {
        .type = 1,
        .args = (iop_mod_attr_arg_t[]){ { .v.p = &tstdox__my_module_c__m_help } },
    },
};
static const iop_mod_attrs_t tstdox__my_module_c__m_desc_attrs = {
    .flags     = 2,
    .attrs_len = 1,
    .attrs     = tstdox__my_module_c__m_attrs,
};
iop_mod_t const tstdox__my_module_c__mod = {
    .fullname   = LSTR_IMMED("tstdox.MyModuleC"),
    .ifaces     = tstdox__my_module_c__aliases,
    .ifaces_len = countof(tstdox__my_module_c__aliases),
    .flags      = 1,
    .mod_attrs  = &tstdox__my_module_c__m_desc_attrs,
    .ifaces_attrs = tstdox__my_module_c__m_desc_if_attrs,
};
iop_mod_t const * const tstdox__my_module_c__modp = &tstdox__my_module_c__mod;

/* }}} */
/* Module tstdox.MyModuleD {{{ */

static iop_iface_alias_t const tstdox__my_module_d__aliases[] = {
    {
        .name  = LSTR_IMMED("ifaceA"),
        .iface = &tstdox__my_iface_a__if,
        .tag   = 1,
    },
    {
        .name  = LSTR_IMMED("ifaceB"),
        .iface = &tstdox__my_iface_b__if,
        .tag   = 2,
    },
    {
        .name  = LSTR_IMMED("ifaceC"),
        .iface = &tstdox__my_iface_c__if,
        .tag   = 3,
    },
};
iop_mod_t const tstdox__my_module_d__mod = {
    .fullname   = LSTR_IMMED("tstdox.MyModuleD"),
    .ifaces     = tstdox__my_module_d__aliases,
    .ifaces_len = countof(tstdox__my_module_d__aliases),
};
iop_mod_t const * const tstdox__my_module_d__modp = &tstdox__my_module_d__mod;

/* }}} */
/* Package tstdox {{{ */

static const iop_pkg_t *const tstdox__deps[] = {
    NULL,
};

static const iop_enum_t *const tstdox__enums[] = {
    &tstdox__my_enum_a__e,
    &tstdox__my_enum_b__e,
    &tstdox__my_enum_c__e,
    &tstdox__my_enum_d__e,
    NULL,
};

static const iop_struct_t *const tstdox__structs[] = {
    &tstdox__my_struct_a__s,
    &tstdox__my_struct_b__s,
    &tstdox__c_data_test__s,
    &tstdox__my_struct_aa__s,
    &tstdox__my_struct_ab__s,
    &tstdox__my_struct_ac__s,
    &tstdox__my_struct_ba__s,
    &tstdox__my_struct_bb__s,
    &tstdox__sort_field__s,
    &tstdox__my_class_base__s,
    &tstdox__my_class_a__s,
    &tstdox__my_class1__s,
    &tstdox__my_class2__s,
    NULL,
};

static const iop_iface_t *const tstdox__ifaces[] = {
    &tstdox__my_iface_a__if,
    &tstdox__my_iface_b__if,
    &tstdox__my_iface_c__if,
    &tstdox__my_iface_d__if,
    NULL,
};

static const iop_mod_t *const tstdox__mods[] = {
    &tstdox__my_module_a__mod,
    &tstdox__my_module_b__mod,
    &tstdox__my_module_c__mod,
    &tstdox__my_module_d__mod,
    NULL,
};

iop_pkg_t const tstdox__pkg = {
    .name    = LSTR_IMMED("tstdox"),
    .deps    = tstdox__deps,
    .enums   = tstdox__enums,
    .structs = tstdox__structs,
    .ifaces  = tstdox__ifaces,
    .mods    = tstdox__mods,
};
iop_pkg_t const * const tstdox__pkgp = &tstdox__pkg;

/* }}} */

