/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef linux
#  warning "tstgen.iop assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "tstgen.iop assumed x86_64 alignments"
#endif

#include "tstgen.iop.h"
#include "pkg_a.iop.h"

/* Enum tstgen.MyEnumA {{{ */

static int const tstgen__my_enum_a__values[] = {
 0, 1, 2,
};
static int const iop__ranges__1[] = {
    0, 0,
    3,
};
static const lstr_t tstgen__my_enum_a__names[] = {
    LSTR_IMMED("VAL_A"),
    LSTR_IMMED("VAL_B"),
    LSTR_IMMED("VAL_C"),
};
static const iop_enum_aliases_t tstgen__my_enum_a__aliases = {
    .aliases = {
        { .pos = 2, .name = LSTR_IMMED("ALIAS_C") },
    },
    .len = 1
};
static const iop_help_t tstgen__my_enum_a__val_a__v_help = {
    .brief = LSTR_IMMED("Test doc + generic attributes on enum value"),
};
static const iop_enum_value_attr_t tstgen__my_enum_a__val_a__v_attrs[] = {
    {
        .type = 5,
        .args = (iop_enum_value_attr_arg_t[]){ { .v.p = &tstgen__my_enum_a__val_a__v_help } },
    },
    {
        .type = 3,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen10") }, { .v.d = 2.00049999999999990e+01 } },
    },
};
static const iop_enum_value_attr_t tstgen__my_enum_a__val_b__v_attrs[] = {
    {
        .type = 2,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen11") }, { .v.i64 = 1UL } },
    },
};
static const iop_enum_value_attr_t tstgen__my_enum_a__val_c__v_attrs[] = {
    {
        .type = 1,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen12") }, {.v.s = LSTR_IMMED("gen7\n") } },
    },
};
static const iop_enum_value_attrs_t tstgen__my_enum_a__e_desc_values_attrs[] = {
    {
        .flags     = 40,
        .attrs_len = 2,
        .attrs     = tstgen__my_enum_a__val_a__v_attrs,
    },
    {
        .flags     = 4,
        .attrs_len = 1,
        .attrs     = tstgen__my_enum_a__val_b__v_attrs,
    },
    {
        .flags     = 2,
        .attrs_len = 1,
        .attrs     = tstgen__my_enum_a__val_c__v_attrs,
    },
};
static const iop_enum_attr_t tstgen__my_enum_a__e_attrs[] = {
    {
        .type = 2,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen1") }, { .v.i64 = 1UL } },
    },
};
static const iop_enum_attrs_t tstgen__my_enum_a__e_desc_attrs = {
    .flags     = 0,
    .attrs_len = 1,
    .attrs     = tstgen__my_enum_a__e_attrs,
};
iop_enum_t const tstgen__my_enum_a__e = {
    .name         = LSTR_IMMED("MyEnumA"),
    .fullname     = LSTR_IMMED("tstgen.MyEnumA"),
    .names        = tstgen__my_enum_a__names,
    .values       = tstgen__my_enum_a__values,
    .ranges       = iop__ranges__1,
    .ranges_len   = countof(iop__ranges__1) / 2,
    .enum_len     = 3,
    .flags        = 5,
    .en_attrs     = &tstgen__my_enum_a__e_desc_attrs,
    .values_attrs = tstgen__my_enum_a__e_desc_values_attrs,
    .aliases      = &tstgen__my_enum_a__aliases,
};
iop_enum_t const * const tstgen__my_enum_a__ep = &tstgen__my_enum_a__e;

/* }}} */
/* Structure tstgen.MyStructA {{{ */

static iop_field_attr_t const tstgen__my_struct_a__j__attrs[] = {
    {
        .type = 14,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen3") }, { .v.d = 1.00000000000000000e+01 } },
    },
};
static iop_field_attr_t const tstgen__my_struct_a__d1__attrs[] = {
    {
        .type = 14,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:d1") }, { .v.d = 1.00000000000000002e-02 } },
    },
    {
        .type = 14,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:d2") }, { .v.d = 1.00000000000000000e+02 } },
    },
};
static iop_field_attrs_t const tstgen__my_struct_a__desc_fields_attrs[] = {
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 16384,
        .attrs_len         = 1,
        .attrs             = tstgen__my_struct_a__j__attrs,
    },
    {
        .flags             = 16384,
        .attrs_len         = 2,
        .attrs             = tstgen__my_struct_a__d1__attrs,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
    {
        .flags             = 0,
        .attrs_len         = 0,
    },
};
static iop_field_t const tstgen__my_struct_a__desc_fields[] = {
    {
        .name      = LSTR_IMMED("i"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstgen__my_struct_a__t, i),
        .size      = fieldsizeof(tstgen__my_struct_a__t, i),
    },
    {
        .name      = LSTR_IMMED("j"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstgen__my_struct_a__t, j),
        .size      = fieldsizeof(tstgen__my_struct_a__t, j),
    },
    {
        .name      = LSTR_IMMED("d1"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_DEFVAL,
        .type      = IOP_T_DOUBLE,
        .data_offs = offsetof(tstgen__my_struct_a__t, d1),
        .u1        = { .defval_d = 1.00000000000000000e+02 },
        .size      = fieldsizeof(tstgen__my_struct_a__t, d1),
    },
    {
        .name      = LSTR_IMMED("weakRef1"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(tstgen__my_struct_a__t, weak_ref1),
        .size      = sizeof(pkg_a__a__t),
        .u1        = { .st_desc = &pkg_a__a__s },
    },
    {
        .name      = LSTR_IMMED("weakRef2"),
        .tag       = 5,
        .tag_len   = 0,
        .repeat    = IOP_R_OPTIONAL,
        .type      = IOP_T_STRUCT,
        .data_offs = offsetof(tstgen__my_struct_a__t, weak_ref2),
        .size      = sizeof(pkg_a__a__t),
        .u1        = { .st_desc = &pkg_a__a__s },
    },
};
static int const iop__ranges__2[] = {
    0, 1,
    5,
};
static const iop_struct_attr_t tstgen__my_struct_a__s_attrs[] = {
    {
        .type = 2,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen2") }, { .v.i64 = 10UL } },
    },
    {
        .type = 1,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen3") }, {.v.s = LSTR_IMMED("test") } },
    },
    {
        .type = 2,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen4") }, { .v.i64 = 0UL } },
    },
};
static const iop_struct_attrs_t tstgen__my_struct_a__s_desc_attrs = {
    .flags     = 0,
    .attrs_len = 3,
    .attrs     = tstgen__my_struct_a__s_attrs,
};
const iop_struct_t tstgen__my_struct_a__s = {
    .fullname   = LSTR_IMMED("tstgen.MyStructA"),
    .fields     = tstgen__my_struct_a__desc_fields,
    .ranges     = iop__ranges__2,
    .ranges_len = countof(iop__ranges__2) / 2,
    .fields_len = countof(tstgen__my_struct_a__desc_fields),
    .size       = sizeof(tstgen__my_struct_a__t),
    .flags      = 1,
    .st_attrs   = &tstgen__my_struct_a__s_desc_attrs,
    .fields_attrs = tstgen__my_struct_a__desc_fields_attrs,
};
iop_struct_t const * const tstgen__my_struct_a__sp = &tstgen__my_struct_a__s;

/* }}} */
/* Union tstgen.MyUnionA {{{ */

static iop_field_t const tstgen__my_union_a__desc_fields[] = {
    {
        .name      = LSTR_IMMED("f1"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_BOOL,
        .data_offs = offsetof(tstgen__my_union_a__t, f1),
        .size      = fieldsizeof(tstgen__my_union_a__t, f1),
    },
    {
        .name      = LSTR_IMMED("f4"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I64,
        .data_offs = offsetof(tstgen__my_union_a__t, f4),
        .size      = fieldsizeof(tstgen__my_union_a__t, f4),
    },
};
static int const iop__ranges__3[] = {
    0, 1,
    1, 4,
    2,
};
const iop_struct_t tstgen__my_union_a__s = {
    .fullname   = LSTR_IMMED("tstgen.MyUnionA"),
    .fields     = tstgen__my_union_a__desc_fields,
    .ranges     = iop__ranges__3,
    .ranges_len = countof(iop__ranges__3) / 2,
    .fields_len = countof(tstgen__my_union_a__desc_fields),
    .size       = sizeof(tstgen__my_union_a__t),
    .is_union   = true,
};
iop_struct_t const * const tstgen__my_union_a__sp = &tstgen__my_union_a__s;

/* }}} */
/* Structure tstgen.Optimized {{{ */

static iop_field_t const tstgen__optimized__desc_fields[] = {
    {
        .name      = LSTR_IMMED("f1"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_BOOL,
        .data_offs = offsetof(tstgen__optimized__t, f1),
        .size      = fieldsizeof(tstgen__optimized__t, f1),
    },
    {
        .name      = LSTR_IMMED("f2"),
        .tag       = 2,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I64,
        .data_offs = offsetof(tstgen__optimized__t, f2),
        .size      = fieldsizeof(tstgen__optimized__t, f2),
    },
    {
        .name      = LSTR_IMMED("f3"),
        .tag       = 3,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_BOOL,
        .data_offs = offsetof(tstgen__optimized__t, f3),
        .size      = fieldsizeof(tstgen__optimized__t, f3),
    },
    {
        .name      = LSTR_IMMED("f4"),
        .tag       = 4,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I64,
        .data_offs = offsetof(tstgen__optimized__t, f4),
        .size      = fieldsizeof(tstgen__optimized__t, f4),
    },
};
static int const iop__ranges__4[] = {
    0, 1,
    4,
};
const iop_struct_t tstgen__optimized__s = {
    .fullname   = LSTR_IMMED("tstgen.Optimized"),
    .fields     = tstgen__optimized__desc_fields,
    .ranges     = iop__ranges__4,
    .ranges_len = countof(iop__ranges__4) / 2,
    .fields_len = countof(tstgen__optimized__desc_fields),
    .size       = sizeof(tstgen__optimized__t),
};
iop_struct_t const * const tstgen__optimized__sp = &tstgen__optimized__s;

/* }}} */
/* Class tstgen.MyClassA {{{ */

static iop_field_t const tstgen__my_class_a__desc_fields[] = {
};
static int const iop__ranges__5[] = {
    0,
};
static const iop_class_attrs_t tstgen__my_class_a__class_s = {
    .class_id          = 0,
};
const iop_struct_t tstgen__my_class_a__s = {
    .fullname   = LSTR_IMMED("tstgen.MyClassA"),
    .fields     = tstgen__my_class_a__desc_fields,
    .ranges     = iop__ranges__5,
    .ranges_len = countof(iop__ranges__5) / 2,
    .fields_len = countof(tstgen__my_class_a__desc_fields),
    .size       = sizeof(tstgen__my_class_a__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &tstgen__my_class_a__class_s,
    }
};
iop_struct_t const * const tstgen__my_class_a__sp = &tstgen__my_class_a__s;

/* }}} */
/* Interface tstgen.MyIfaceA {{{ */
/* Structure tstgen.MyIfaceA.funAArgs {{{ */

static iop_field_t const tstgen__my_iface_a__fun_a_args__desc_fields[] = {
    {
        .name      = LSTR_IMMED("a"),
        .tag       = 1,
        .tag_len   = 0,
        .repeat    = IOP_R_REQUIRED,
        .type      = IOP_T_I32,
        .data_offs = offsetof(tstgen__my_iface_a__fun_a_args__t, a),
        .size      = fieldsizeof(tstgen__my_iface_a__fun_a_args__t, a),
    },
};
static int const iop__ranges__6[] = {
    0, 1,
    1,
};
const iop_struct_t tstgen__my_iface_a__fun_a_args__s = {
    .fullname   = LSTR_IMMED("tstgen.MyIfaceA.funAArgs"),
    .fields     = tstgen__my_iface_a__fun_a_args__desc_fields,
    .ranges     = iop__ranges__6,
    .ranges_len = countof(iop__ranges__6) / 2,
    .fields_len = countof(tstgen__my_iface_a__fun_a_args__desc_fields),
    .size       = sizeof(tstgen__my_iface_a__fun_a_args__t),
};
iop_struct_t const * const tstgen__my_iface_a__fun_a_args__sp = &tstgen__my_iface_a__fun_a_args__s;

/* }}} */
static iop_rpc_t const tstgen__my_iface_a__if_funs[] = {
    {
        .name      = LSTR_IMMED("funB"),
        .tag       = 1,
        .args      = &iop__void__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
        .async     = true,
    },
    {
        .name      = LSTR_IMMED("funA"),
        .tag       = 2,
        .args      = &tstgen__my_iface_a__fun_a_args__s,
        .result    = &iop__void__s,
        .exn       = &iop__void__s,
    },
};
static iop_rpc_attr_t const tstgen__my_iface_a__fun_a__attrs[] = {
    {
        .type = 7,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen5") }, { .v.d = 2.00049999999999990e+01 } },
    },
    {
        .type = 6,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen6") }, { .v.i64 = 1UL } },
    },
    {
        .type = 5,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen7") }, {.v.s = LSTR_IMMED("gen7") } },
    },
};
static iop_rpc_attrs_t const tstgen__my_iface_a__rpc_desc_attrs[] = {
    {
        .flags             = 0,
    },
    {
        .flags             = 224,
        .attrs_len         = 3,
        .attrs             = tstgen__my_iface_a__fun_a__attrs,
    },
};
static const iop_iface_attr_t tstgen__my_iface_a__if_attrs[] = {
    {
        .type = 1,
        .args = (iop_field_attr_arg_t[]){ { .v.s = LSTR_IMMED("test:gen4") }, {.v.s = LSTR_IMMED("test") } },
    },
};
static const iop_iface_attrs_t tstgen__my_iface_a__desc_if_attrs = {
    .flags     = 0,
    .attrs_len = 1,
    .attrs     = tstgen__my_iface_a__if_attrs,
};
const iop_iface_t tstgen__my_iface_a__if = {
    .fullname   = LSTR_IMMED("tstgen.MyIfaceA"),
    .funs       = tstgen__my_iface_a__if_funs,
    .funs_len   = countof(tstgen__my_iface_a__if_funs),
    .flags      = 3,
    .rpc_attrs  = tstgen__my_iface_a__rpc_desc_attrs,
    .iface_attrs  = &tstgen__my_iface_a__desc_if_attrs,
};
const iop_iface_t * const tstgen__my_iface_a__ifp = &tstgen__my_iface_a__if;

/* }}} */
/* Package tstgen {{{ */

static const iop_pkg_t *const tstgen__deps[] = {
    NULL,
};

static const iop_enum_t *const tstgen__enums[] = {
    &tstgen__my_enum_a__e,
    NULL,
};

static const iop_struct_t *const tstgen__structs[] = {
    &tstgen__my_struct_a__s,
    &tstgen__my_union_a__s,
    &tstgen__optimized__s,
    &tstgen__my_class_a__s,
    NULL,
};

static const iop_iface_t *const tstgen__ifaces[] = {
    &tstgen__my_iface_a__if,
    NULL,
};

static const iop_mod_t *const tstgen__mods[] = {
    NULL,
};

iop_pkg_t const tstgen__pkg = {
    .name    = LSTR_IMMED("tstgen"),
    .deps    = tstgen__deps,
    .enums   = tstgen__enums,
    .structs = tstgen__structs,
    .ifaces  = tstgen__ifaces,
    .mods    = tstgen__mods,
};
iop_pkg_t const * const tstgen__pkgp = &tstgen__pkg;

/* }}} */

