/***************************************************************************/
/*                                                                         */
/* Copyright 2026 INTERSEC SA                                              */
/*                                                                         */
/* Licensed under the Apache License, Version 2.0 (the "License");         */
/* you may not use this file except in compliance with the License.        */
/* You may obtain a copy of the License at                                 */
/*                                                                         */
/*     http://www.apache.org/licenses/LICENSE-2.0                          */
/*                                                                         */
/* Unless required by applicable law or agreed to in writing, software     */
/* distributed under the License is distributed on an "AS IS" BASIS,       */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and     */
/* limitations under the License.                                          */
/*                                                                         */
/***************************************************************************/

//! Shared core of the Rust wrappers around the C hash tables.
//!
//! This module holds what every table wrapper shares: the [`QHashType`] trait that the generated
//! code implements, and the [`QEntryWipe`] trait that names the destructor of the entries.
//!
//! The wrappers are generic over the C table type, not over the key and value types: a C table
//! carries its own hash and equality functions, so the table type is the only thing that can name
//! the key type. The key and value types come from the [`QHashType`] implementation.

use crate::bindings::mem_pool_t;

// {{{ QHashType

/// Trait implemented by every `qh_t` and `qm_t` type generated by `bindgen`.
///
/// A C table embeds its own hash and equality functions, so every operation that needs them has to
/// go through the functions that the C macros generated for that table. This trait gathers them.
///
/// The implementations are generated by `waf-cargo-build`; do not write them by hand.
///
/// # Safety
///
/// The implementor must have the layout of a `qhash_t`, [`Self::Key`] and [`Self::Value`] must be
/// the exact key and value types of the C table, and every method must forward to the functions
/// that C generated for that table.
pub unsafe trait QHashType: Sized {
    /// The key type of the C table.
    type Key;

    /// The value type of the C table, `()` for a set.
    type Value;

    /// Initialize the table.
    ///
    /// # Safety
    ///
    /// `qh` must point to writable memory of the size of `Self`.
    unsafe fn init(qh: *mut Self, cached: bool, mp: *mut mem_pool_t);

    /// Get the hash of a key.
    ///
    /// # Safety
    ///
    /// `qh` must point to an initialized table.
    unsafe fn hash(qh: *const Self, key: &Self::Key) -> u32;

    /// Get the position of a key, or a negative value if it is absent.
    ///
    /// This can complete a running resize of the table.
    ///
    /// # Safety
    ///
    /// `qh` must point to an initialized table.
    unsafe fn find(qh: *mut Self, key: &Self::Key) -> i32;

    /// Get the position of a key, or a negative value if it is absent.
    ///
    /// This never modifies the table.
    ///
    /// # Safety
    ///
    /// `qh` must point to an initialized table.
    unsafe fn find_safe(qh: *const Self, key: &Self::Key) -> i32;

    /// Reserve the slot of a key and store the key in it.
    ///
    /// The returned position has the `QHASH_COLLISION` bit set if the key was already there.
    ///
    /// # Safety
    ///
    /// `qh` must point to an initialized table that is not sealed.
    unsafe fn reserve(qh: *mut Self, key: &Self::Key, flags: u32) -> u32;

    /// Seal the table, which forbids any further modification.
    ///
    /// # Safety
    ///
    /// `qh` must point to an initialized table.
    unsafe fn seal(qh: *mut Self);
}

// }}}
// {{{ QEntryWipe

/// Releases what the entries of a table own.
///
/// A C table holds plain C data, so it cannot drop its entries the way a `Vec` does. This trait
/// carries the destructor instead: it is the `wipe` argument of the C `qh_deep_wipe()`, named by a
/// type rather than passed at every call.
///
/// It is a type parameter of the table types rather than a field of them, so that a table
/// keeps the layout of its C type and can still be handed to C without a copy.
///
/// # Example
///
/// ```ignore
/// struct WipeKey;
///
/// impl<Q: QHashType<Key = lstr_t>> QEntryWipe<Q> for WipeKey {
///     fn wipe_key(key: &mut lstr_t) {
///         unsafe { lstr_wipe(key) };
///     }
///
///     fn wipe_value(_value: &mut Q::Value) {}
/// }
/// ```
pub trait QEntryWipe<Q: QHashType> {
    /// Whether the entries own anything.
    ///
    /// [`NoWipe`] sets it to `false`, which lets a table skip the scan of its entries when it is
    /// cleared or dropped.
    const WIPES: bool = true;

    /// Release what a key owns.
    fn wipe_key(key: &mut Q::Key);

    /// Release what a value owns.
    fn wipe_value(value: &mut Q::Value);
}

/// Destructor of a table whose entries own nothing.
///
/// This is the behaviour of the C `qh_wipe()`, and the default for every table.
pub struct NoWipe;

impl<Q: QHashType> QEntryWipe<Q> for NoWipe {
    const WIPES: bool = false;

    fn wipe_key(_key: &mut Q::Key) {}

    fn wipe_value(_value: &mut Q::Value) {}
}

// }}}
