/***************************************************************************/
/*                                                                         */
/* Copyright 2026 INTERSEC SA                                              */
/*                                                                         */
/* Licensed under the Apache License, Version 2.0 (the "License");         */
/* you may not use this file except in compliance with the License.        */
/* You may obtain a copy of the License at                                 */
/*                                                                         */
/*     http://www.apache.org/licenses/LICENSE-2.0                          */
/*                                                                         */
/* Unless required by applicable law or agreed to in writing, software     */
/* distributed under the License is distributed on an "AS IS" BASIS,       */
/* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.*/
/* See the License for the specific language governing permissions and     */
/* limitations under the License.                                          */
/*                                                                         */
/***************************************************************************/

//! Module to interact with `qv_t` (qvector) in Rust.
//!
//! [`QVector`] wraps a C `qvector_t` and behaves like a [`Vec`]. It derefs to a slice, so the
//! whole slice API (indexing, iteration, sorting, searching) is available on it.
//!
//! # Allocator
//!
//! The allocator is chosen by the constructor and cannot change afterwards:
//!
//! - [`QVector::new`] allocates with libc.
//! - [`QVector::t_new`] allocates on the `t_pool` of a [`TScope`]. The vector borrows the
//!   [`TScope`], so it cannot outlive it.
//! - [`QVector::from_stack_buffer`] starts on a caller-provided buffer, and falls back to libc if
//!   it has to grow.
//!
//! # Element ownership
//!
//! A [`QVector`] owns its elements: they are dropped when the vector is dropped. This is the
//! equivalent of the C `qv_deep_wipe()`. Use an owning element type to get it:
//!
//! - `QVector<lstr_t>` only frees its buffer, like the C `qv_wipe()`. Use it for vectors of
//!   borrowed values, which is what most C functions fill.
//! - `QVector<OwnedUtf8Lstr>` also calls `lstr_wipe()` on every element, like the C
//!   `qv_deep_wipe()`.
//!
//! Both have the same layout, so both can be passed to C.
//!
//! # Interfacing with C
//!
//! Every generated `qv_t` type implements [`QVectorType`]. Use [`QVector::as_mut_c_ptr`] to pass a
//! vector to a C function, and [`QVector::borrow_c_mut`] to manipulate a vector owned by C.

use std::fmt;
use std::iter::FusedIterator;
use std::marker::PhantomData;
use std::mem::{ManuallyDrop, MaybeUninit};
use std::ops::{Deref, DerefMut};
use std::os::raw::c_int;
use std::ptr;
use std::slice;

use crate::bindings::{
    __qvector_grow, mem_pool_static, mem_pool_t, qvector_growlen, qvector_optimize, qvector_reset,
    qvector_splice, qvector_t, qvector_wipe, t_pool,
};
use crate::helpers::{slice_from_nullable_raw_parts, slice_from_nullable_raw_parts_mut};
use crate::mem_stack::TScope;

// {{{ QVectorType

/// Trait implemented by every `qv_t` type generated by `bindgen`.
///
/// It binds a C vector type to its element type, so that a [`QVector`] can be converted to and
/// from the matching C type.
///
/// The implementations are generated by `waf-cargo-build`; do not write them by hand.
///
/// # Safety
///
/// The implementor must have the layout of a `qvector_t`, and [`Self::Element`] must be the exact
/// element type of the C vector.
pub unsafe trait QVectorType {
    /// The element type of the C vector.
    type Element;
}

// }}}
// {{{ QVector

/// Wrapper around a C `qv_t` for safe manipulation in Rust.
///
/// See the [module documentation](self) for the allocator and element ownership rules.
#[repr(transparent)]
pub struct QVector<'a, T> {
    qv: qvector_t,

    // `&'a ()` ties the vector to its allocator scope, `T` makes the vector own its elements.
    _marker: PhantomData<(&'a (), T)>,
}

// The C code accesses the vector through a `qvector_t` pointer.
const _: () = {
    assert!(size_of::<QVector<'static, u8>>() == size_of::<qvector_t>());
    assert!(align_of::<QVector<'static, u8>>() == align_of::<qvector_t>());
};

impl<'a, T> QVector<'a, T> {
    // {{{ Constructors

    /// Create an empty vector allocated by libc.
    pub const fn new() -> Self {
        Self::with_mp(ptr::null_mut())
    }

    /// Create a vector allocated by libc with room for `capacity` elements.
    pub fn with_capacity(capacity: usize) -> Self {
        let mut vec = Self::new();

        vec.reserve(capacity);
        vec
    }

    /// Create an empty vector allocated on the `t_pool` of `t_scope`.
    ///
    /// The vector borrows the [`TScope`], so it is dropped before the scope is popped.
    pub fn t_new(_t_scope: &'a TScope) -> Self {
        Self::with_mp(unsafe { t_pool() })
    }

    /// Create a vector allocated on the `t_pool` of `t_scope` with room for `capacity` elements.
    pub fn t_with_capacity(t_scope: &'a TScope, capacity: usize) -> Self {
        let mut vec = Self::t_new(t_scope);

        vec.reserve(capacity);
        vec
    }

    /// Create an empty vector using a caller-provided buffer.
    ///
    /// This is the equivalent of the C `qv_inita()`. The vector uses `mem_pool_static`, so it
    /// falls back to libc if it grows past the buffer.
    ///
    /// # Panics
    ///
    /// The buffer length does not fit in a C `int`.
    pub fn from_stack_buffer(buffer: &'a mut [MaybeUninit<T>]) -> Self {
        let size = c_int::try_from(buffer.len()).expect("buffer too large for a qvector");

        Self {
            qv: qvector_t {
                tab: buffer.as_mut_ptr().cast::<u8>(),
                mp: &raw mut mem_pool_static,
                len: 0,
                size,
            },
            _marker: PhantomData,
        }
    }

    /// Create an empty vector using the given memory pool.
    const fn with_mp(mp: *mut mem_pool_t) -> Self {
        Self {
            qv: qvector_t {
                tab: ptr::null_mut(),
                mp,
                len: 0,
                size: 0,
            },
            _marker: PhantomData,
        }
    }

    /// Collect an iterator into a vector allocated on the `t_pool` of `t_scope`.
    ///
    /// This is the `t_pool` counterpart of [`Iterator::collect`], which can only build a vector
    /// allocated by libc because it cannot receive a [`TScope`].
    pub fn t_from_iter<I>(t_scope: &'a TScope, iter: I) -> Self
    where
        I: IntoIterator<Item = T>,
    {
        let iter = iter.into_iter();
        let mut vec = Self::t_with_capacity(t_scope, iter.size_hint().0);

        vec.extend(iter);
        vec
    }

    // }}}
    // {{{ Accessors

    /// Get the number of elements of the vector.
    #[inline]
    pub const fn len(&self) -> usize {
        self.qv.len as usize
    }

    /// Check whether the vector is empty.
    #[inline]
    pub const fn is_empty(&self) -> bool {
        self.qv.len == 0
    }

    /// Get the number of elements the vector can hold without reallocating.
    #[inline]
    pub const fn capacity(&self) -> usize {
        self.qv.size as usize
    }

    /// Get the elements of the vector as a slice.
    #[inline]
    pub const fn as_slice(&self) -> &[T] {
        unsafe { slice_from_nullable_raw_parts(self.qv.tab.cast::<T>(), self.len()) }
    }

    /// Get the elements of the vector as a mutable slice.
    #[inline]
    pub const fn as_mut_slice(&mut self) -> &mut [T] {
        unsafe { slice_from_nullable_raw_parts_mut(self.qv.tab.cast::<T>(), self.len()) }
    }

    /// Get a raw pointer to the elements of the vector.
    ///
    /// The pointer is null if the vector never allocated.
    #[inline]
    pub const fn as_ptr(&self) -> *const T {
        self.qv.tab.cast::<T>()
    }

    /// Get a mutable raw pointer to the elements of the vector.
    ///
    /// The pointer is null if the vector never allocated.
    #[inline]
    pub const fn as_mut_ptr(&mut self) -> *mut T {
        self.qv.tab.cast::<T>()
    }

    // }}}
    // {{{ Capacity

    /// Reserve room for at least `additional` more elements.
    ///
    /// The capacity is never reduced.
    ///
    /// # Panics
    ///
    /// The resulting length does not fit in a C `int`.
    pub fn reserve(&mut self, additional: usize) {
        let len = self.len();

        if len + additional <= self.capacity() {
            return;
        }
        Self::assert_c_len(len + additional);

        unsafe {
            __qvector_grow(
                &raw mut self.qv,
                size_of::<T>(),
                align_of::<T>(),
                additional as c_int,
            );
        }
    }

    /// Release the memory that the vector does not use.
    pub fn shrink_to_fit(&mut self) {
        unsafe {
            qvector_optimize(&raw mut self.qv, size_of::<T>(), align_of::<T>(), 0, 0);
        }
    }

    // }}}
    // {{{ Mutators

    /// Append an element to the vector.
    ///
    /// # Panics
    ///
    /// The resulting length does not fit in a C `int`.
    pub fn push(&mut self, value: T) {
        assert!(self.qv.len < c_int::MAX, "qvector length overflow");

        let slot = unsafe { qvector_growlen(&raw mut self.qv, size_of::<T>(), align_of::<T>(), 1) };

        unsafe {
            slot.cast::<T>().write(value);
        }
    }

    /// Remove the last element of the vector and return it, or `None` if it is empty.
    pub fn pop(&mut self) -> Option<T> {
        let len = self.len();

        if len == 0 {
            return None;
        }
        self.qv.len -= 1;
        Some(unsafe { self.as_ptr().add(len - 1).read() })
    }

    /// Insert an element at `index`, shifting the following elements to the right.
    ///
    /// # Panics
    ///
    /// `index` is greater than the length, or the resulting length does not fit in a C `int`.
    pub fn insert(&mut self, index: usize, value: T) {
        assert!(index <= self.len(), "insertion index out of bounds");
        assert!(self.qv.len < c_int::MAX, "qvector length overflow");

        let slot = unsafe {
            qvector_splice(
                &raw mut self.qv,
                size_of::<T>(),
                align_of::<T>(),
                index as c_int,
                0,
                ptr::null(),
                1,
            )
        };

        unsafe {
            slot.cast::<T>().write(value);
        }
    }

    /// Remove the element at `index` and return it, shifting the following elements to the left.
    ///
    /// # Panics
    ///
    /// `index` is out of bounds.
    pub fn remove(&mut self, index: usize) -> T {
        assert!(index < self.len(), "removal index out of bounds");

        let value = unsafe { self.as_ptr().add(index).read() };

        unsafe {
            qvector_splice(
                &raw mut self.qv,
                size_of::<T>(),
                align_of::<T>(),
                index as c_int,
                1,
                ptr::null(),
                0,
            );
        }
        value
    }

    /// Remove the element at `index` and return it, replacing it with the last element.
    ///
    /// This does not preserve the order of the elements, but runs in constant time.
    ///
    /// # Panics
    ///
    /// `index` is out of bounds.
    pub fn swap_remove(&mut self, index: usize) -> T {
        let len = self.len();

        assert!(index < len, "swap_remove index out of bounds");

        unsafe {
            let tab = self.as_mut_ptr();
            let value = tab.add(index).read();

            if index + 1 != len {
                ptr::copy_nonoverlapping(tab.add(len - 1), tab.add(index), 1);
            }
            self.qv.len -= 1;
            value
        }
    }

    /// Drop the elements after the first `len` ones.
    ///
    /// This does nothing if `len` is greater than the length.
    pub fn truncate(&mut self, len: usize) {
        let old_len = self.len();

        if len >= old_len {
            return;
        }

        // Shorten the vector first, so that the elements are not dropped twice if dropping one of
        // them panics.
        self.qv.len = len as c_int;

        let tail =
            ptr::slice_from_raw_parts_mut(unsafe { self.as_mut_ptr().add(len) }, old_len - len);

        unsafe {
            ptr::drop_in_place(tail);
        }
    }

    /// Drop every element of the vector.
    ///
    /// The buffer is kept, unless it is large enough that the C code decides to release it.
    pub fn clear(&mut self) {
        self.truncate(0);
        unsafe {
            qvector_reset(&raw mut self.qv, size_of::<T>());
        }
    }

    /// Append a copy of every element of `other` to the vector.
    ///
    /// # Panics
    ///
    /// The resulting length does not fit in a C `int`.
    pub fn extend_from_slice(&mut self, other: &[T])
    where
        T: Copy,
    {
        if other.is_empty() {
            return;
        }

        Self::assert_c_len(self.len() + other.len());

        let extra = Self::to_c_int(other.len());
        let slot =
            unsafe { qvector_growlen(&raw mut self.qv, size_of::<T>(), align_of::<T>(), extra) };

        unsafe {
            ptr::copy_nonoverlapping(other.as_ptr(), slot.cast::<T>(), other.len());
        }
    }

    // }}}
    // {{{ C interoperability

    /// Get the vector as a pointer to the matching C `qv_t` type.
    #[inline]
    pub const fn as_c_ptr<Q>(&self) -> *const Q
    where
        Q: QVectorType<Element = T>,
        T: Copy,
    {
        (&raw const self.qv).cast::<Q>()
    }

    /// Get the vector as a mutable pointer to the matching C `qv_t` type.
    ///
    /// The element type is `Copy`, so the C code cannot make the vector own resources that it
    /// would then have to release. Use [`Self::as_mut_c_ptr_unchecked`] for an owning element
    /// type.
    #[inline]
    pub const fn as_mut_c_ptr<Q>(&mut self) -> *mut Q
    where
        Q: QVectorType<Element = T>,
        T: Copy,
    {
        (&raw mut self.qv).cast::<Q>()
    }

    /// Get the vector as a mutable pointer to the matching C `qv_t` type, for any element type.
    ///
    /// # Safety
    ///
    /// The vector owns its elements: it drops them when it is dropped. The C code must leave it
    /// with `len` elements that it is allowed to drop. In particular, a C function that fills the
    /// vector with borrowed values must not be called through this method.
    #[inline]
    pub const unsafe fn as_mut_c_ptr_unchecked<Q>(&mut self) -> *mut Q
    where
        Q: QVectorType<Element = T>,
    {
        (&raw mut self.qv).cast::<Q>()
    }

    /// Borrow a C vector as a [`QVector`].
    ///
    /// The C vector keeps its ownership: the returned reference never drops it.
    ///
    /// # Safety
    ///
    /// `qv` must be a valid C vector: its first `len` elements must be initialized.
    #[inline]
    pub const unsafe fn borrow_c<Q>(qv: &Q) -> &Self
    where
        Q: QVectorType<Element = T>,
    {
        unsafe { &*ptr::from_ref(qv).cast::<Self>() }
    }

    /// Borrow a C vector as a mutable [`QVector`].
    ///
    /// The C vector keeps its ownership: the returned reference never drops it.
    ///
    /// # Safety
    ///
    /// `qv` must be a valid C vector: its first `len` elements must be initialized.
    #[inline]
    pub const unsafe fn borrow_c_mut<Q>(qv: &mut Q) -> &mut Self
    where
        Q: QVectorType<Element = T>,
    {
        unsafe { &mut *ptr::from_mut(qv).cast::<Self>() }
    }

    // }}}
    // {{{ Helpers

    /// Convert a length to a C `int`.
    ///
    /// # Panics
    ///
    /// The length does not fit in a C `int`.
    fn to_c_int(len: usize) -> c_int {
        c_int::try_from(len).expect("qvector length overflow")
    }

    /// Check that a length fits in a C `int`.
    ///
    /// # Panics
    ///
    /// The length does not fit in a C `int`.
    fn assert_c_len(len: usize) {
        assert!(c_int::try_from(len).is_ok(), "qvector length overflow");
    }

    // }}}
}

// }}}
// {{{ QVector trait implementations

impl<T> Drop for QVector<'_, T> {
    fn drop(&mut self) {
        // Drop the elements, then release the buffer. `qvector_wipe()` only releases the buffer
        // for the pools that are not frame-based, so this is correct for every allocator.
        let elements = ptr::slice_from_raw_parts_mut(self.as_mut_ptr(), self.len());

        unsafe {
            ptr::drop_in_place(elements);
            qvector_wipe(&raw mut self.qv, size_of::<T>());
        }
    }
}

impl<T> Default for QVector<'_, T> {
    fn default() -> Self {
        Self::new()
    }
}

impl<T> Deref for QVector<'_, T> {
    type Target = [T];

    #[inline]
    fn deref(&self) -> &Self::Target {
        self.as_slice()
    }
}

impl<T> DerefMut for QVector<'_, T> {
    #[inline]
    fn deref_mut(&mut self) -> &mut Self::Target {
        self.as_mut_slice()
    }
}

impl<T> AsRef<[T]> for QVector<'_, T> {
    fn as_ref(&self) -> &[T] {
        self.as_slice()
    }
}

impl<T> AsMut<[T]> for QVector<'_, T> {
    fn as_mut(&mut self) -> &mut [T] {
        self.as_mut_slice()
    }
}

impl<T: fmt::Debug> fmt::Debug for QVector<'_, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_list().entries(self.as_slice()).finish()
    }
}

impl<T: PartialEq<U>, U> PartialEq<QVector<'_, U>> for QVector<'_, T> {
    fn eq(&self, other: &QVector<'_, U>) -> bool {
        self.as_slice() == other.as_slice()
    }
}

impl<T: Eq> Eq for QVector<'_, T> {}

impl<T: PartialEq<U>, U> PartialEq<[U]> for QVector<'_, T> {
    fn eq(&self, other: &[U]) -> bool {
        self.as_slice() == other
    }
}

impl<T: PartialEq<U>, U, const N: usize> PartialEq<[U; N]> for QVector<'_, T> {
    fn eq(&self, other: &[U; N]) -> bool {
        self.as_slice() == other.as_slice()
    }
}

/// Clone the vector, keeping the allocator of the source.
impl<T: Clone> Clone for QVector<'_, T> {
    fn clone(&self) -> Self {
        let mut vec = Self::with_mp(self.qv.mp);

        vec.reserve(self.len());
        vec.extend(self.as_slice().iter().cloned());
        vec
    }
}

impl<T> Extend<T> for QVector<'_, T> {
    fn extend<I: IntoIterator<Item = T>>(&mut self, iter: I) {
        let iter = iter.into_iter();

        self.reserve(iter.size_hint().0);
        for value in iter {
            self.push(value);
        }
    }
}

impl<'x, T: Copy + 'x> Extend<&'x T> for QVector<'_, T> {
    fn extend<I: IntoIterator<Item = &'x T>>(&mut self, iter: I) {
        let iter = iter.into_iter();

        self.reserve(iter.size_hint().0);
        for value in iter {
            self.push(*value);
        }
    }
}

/// Collect an iterator into a vector allocated by libc.
///
/// Use [`QVector::t_from_iter`] to collect into a vector allocated on a `t_pool`.
impl<T> FromIterator<T> for QVector<'_, T> {
    fn from_iter<I: IntoIterator<Item = T>>(iter: I) -> Self {
        let iter = iter.into_iter();
        let mut vec = Self::with_capacity(iter.size_hint().0);

        vec.extend(iter);
        vec
    }
}

impl<'x, T> IntoIterator for &'x QVector<'_, T> {
    type Item = &'x T;
    type IntoIter = slice::Iter<'x, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.as_slice().iter()
    }
}

impl<'x, T> IntoIterator for &'x mut QVector<'_, T> {
    type Item = &'x mut T;
    type IntoIter = slice::IterMut<'x, T>;

    fn into_iter(self) -> Self::IntoIter {
        self.as_mut_slice().iter_mut()
    }
}

impl<'a, T> IntoIterator for QVector<'a, T> {
    type Item = T;
    type IntoIter = IntoIter<'a, T>;

    fn into_iter(self) -> Self::IntoIter {
        let end = self.len();

        IntoIter {
            vec: ManuallyDrop::new(self),
            start: 0,
            end,
        }
    }
}

// }}}
// {{{ IntoIter

/// Owning iterator over the elements of a [`QVector`].
///
/// It is created by the [`IntoIterator`] implementation of [`QVector`].
pub struct IntoIter<'a, T> {
    vec: ManuallyDrop<QVector<'a, T>>,
    start: usize,
    end: usize,
}

impl<T> Iterator for IntoIter<'_, T> {
    type Item = T;

    fn next(&mut self) -> Option<T> {
        if self.start == self.end {
            return None;
        }

        let value = unsafe { self.vec.as_ptr().add(self.start).read() };

        self.start += 1;
        Some(value)
    }

    fn size_hint(&self) -> (usize, Option<usize>) {
        let remaining = self.end - self.start;

        (remaining, Some(remaining))
    }
}

impl<T> DoubleEndedIterator for IntoIter<'_, T> {
    fn next_back(&mut self) -> Option<T> {
        if self.start == self.end {
            return None;
        }
        self.end -= 1;
        Some(unsafe { self.vec.as_ptr().add(self.end).read() })
    }
}

impl<T> ExactSizeIterator for IntoIter<'_, T> {}

impl<T> FusedIterator for IntoIter<'_, T> {}

impl<T: fmt::Debug> fmt::Debug for IntoIter<'_, T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_list().entries(self.as_slice()).finish()
    }
}

impl<T> IntoIter<'_, T> {
    /// Get the elements that the iterator did not yield yet.
    #[inline]
    pub fn as_slice(&self) -> &[T] {
        let tab = self.vec.as_ptr();

        if tab.is_null() {
            return &[];
        }

        unsafe { slice::from_raw_parts(tab.add(self.start), self.len_left()) }
    }

    /// Get the number of elements that the iterator did not yield yet.
    #[inline]
    const fn len_left(&self) -> usize {
        self.end - self.start
    }
}

impl<T> Drop for IntoIter<'_, T> {
    fn drop(&mut self) {
        // Drop the elements that were not yielded.
        let tab = self.vec.as_mut_ptr();

        if !tab.is_null() {
            let left =
                ptr::slice_from_raw_parts_mut(unsafe { tab.add(self.start) }, self.len_left());

            unsafe {
                ptr::drop_in_place(left);
            }
        }

        // Every element is dropped: let the vector release its buffer only.
        self.vec.qv.len = 0;
        unsafe {
            ManuallyDrop::drop(&mut self.vec);
        }
    }
}

// }}}
// {{{ Tests

#[cfg(test)]
#[allow(clippy::redundant_test_prefix)]
mod tests {
    use std::cell::Cell;
    use std::mem;
    use std::os::raw::c_char;
    use std::ptr;

    use super::*;
    use crate::bindings::{ctype_isspace, lstr_t, ps_split, qv_lstr_t, qv_str_t, qv_u32_t};
    use crate::lstr::{self, OwnedUtf8Lstr, from_str};
    use crate::pstream::pstream_t;

    // {{{ Test helpers

    /// Split a string with the C `ps_split()` into a C vector.
    ///
    /// The returned vector holds values borrowed from `input`.
    fn c_split(input: &str) -> qv_lstr_t {
        let ps = pstream_t::from_bytes(input.as_bytes());
        let mut c_vec: qv_lstr_t = unsafe { mem::zeroed() };

        unsafe {
            ps_split(ps, &raw const ctype_isspace, 0, &raw mut c_vec);
        }
        c_vec
    }

    /// Read the C vector values as Rust strings.
    fn to_strings(values: &[lstr_t]) -> Vec<&str> {
        values
            .iter()
            .map(|raw| unsafe { lstr::from_raw_utf8(*raw).as_str() })
            .collect()
    }

    /// Element type that counts its drops, to check that the vector owns its elements.
    struct DropCounter<'c> {
        counter: &'c Cell<usize>,
    }

    impl Drop for DropCounter<'_> {
        fn drop(&mut self) {
            self.counter.set(self.counter.get() + 1);
        }
    }

    /// Fill a vector with `DropCounter` elements.
    fn push_counters<'c>(
        vec: &mut QVector<'_, DropCounter<'c>>,
        counter: &'c Cell<usize>,
        n: usize,
    ) {
        for _ in 0..n {
            vec.push(DropCounter { counter });
        }
    }

    // }}}
    // {{{ Layout

    #[test]
    fn test_layout() {
        assert_eq!(size_of::<QVector<'static, u32>>(), size_of::<qvector_t>());
        assert_eq!(align_of::<QVector<'static, u32>>(), align_of::<qvector_t>());
    }

    // }}}
    // {{{ Basic operations

    #[test]
    fn test_new_is_empty() {
        let vec = QVector::<u32>::new();

        assert!(vec.is_empty());
        assert_eq!(vec.len(), 0);
        assert_eq!(vec.capacity(), 0);
        assert_eq!(vec.as_slice(), &[] as &[u32]);
        assert!(vec.as_ptr().is_null());
    }

    #[test]
    fn test_default() {
        let vec = QVector::<u32>::default();

        assert!(vec.is_empty());
    }

    #[test]
    fn test_push_pop() {
        let mut vec = QVector::<u32>::new();

        vec.push(1);
        vec.push(2);
        vec.push(3);

        assert_eq!(vec.len(), 3);
        assert!(vec.capacity() >= 3);
        assert_eq!(vec.as_slice(), &[1, 2, 3]);

        assert_eq!(vec.pop(), Some(3));
        assert_eq!(vec.pop(), Some(2));
        assert_eq!(vec.pop(), Some(1));
        assert_eq!(vec.pop(), None);
        assert!(vec.is_empty());
    }

    #[test]
    fn test_push_many_reallocations() {
        let mut vec = QVector::<u64>::new();

        for i in 0..10_000 {
            vec.push(i);
        }

        assert_eq!(vec.len(), 10_000);
        assert_eq!(vec.first(), Some(&0));
        assert_eq!(vec.last(), Some(&9_999));
        assert_eq!(vec.iter().sum::<u64>(), (0..10_000).sum::<u64>());
    }

    #[test]
    fn test_with_capacity() {
        let vec = QVector::<u32>::with_capacity(64);

        assert!(vec.is_empty());
        assert!(vec.capacity() >= 64);

        // A zero capacity must not allocate.
        let vec = QVector::<u32>::with_capacity(0);

        assert_eq!(vec.capacity(), 0);
    }

    #[test]
    fn test_reserve_never_shrinks() {
        let mut vec = QVector::<u32>::with_capacity(1024);
        let capacity = vec.capacity();

        vec.push(1);
        vec.reserve(1);

        assert_eq!(vec.capacity(), capacity);
    }

    #[test]
    fn test_insert_remove() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[1, 2, 3]);

        vec.insert(1, 10);
        assert_eq!(vec.as_slice(), &[1, 10, 2, 3]);

        vec.insert(0, 20);
        assert_eq!(vec.as_slice(), &[20, 1, 10, 2, 3]);

        vec.insert(5, 30);
        assert_eq!(vec.as_slice(), &[20, 1, 10, 2, 3, 30]);

        assert_eq!(vec.remove(0), 20);
        assert_eq!(vec.remove(4), 30);
        assert_eq!(vec.as_slice(), &[1, 10, 2, 3]);
    }

    #[test]
    fn test_swap_remove() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[1, 2, 3, 4]);

        assert_eq!(vec.swap_remove(0), 1);
        assert_eq!(vec.as_slice(), &[4, 2, 3]);

        assert_eq!(vec.swap_remove(2), 3);
        assert_eq!(vec.as_slice(), &[4, 2]);
    }

    #[test]
    fn test_truncate_and_clear() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[1, 2, 3, 4, 5]);

        // A length greater than the current one does nothing.
        vec.truncate(10);
        assert_eq!(vec.len(), 5);

        vec.truncate(2);
        assert_eq!(vec.as_slice(), &[1, 2]);

        vec.clear();
        assert!(vec.is_empty());
    }

    #[test]
    fn test_extend_from_slice() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[]);
        assert!(vec.is_empty());

        vec.extend_from_slice(&[1, 2]);
        vec.extend_from_slice(&[3, 4]);
        assert_eq!(vec.as_slice(), &[1, 2, 3, 4]);
    }

    #[test]
    fn test_shrink_to_fit() {
        let mut vec = QVector::<u32>::with_capacity(1024);

        vec.extend_from_slice(&[1, 2, 3]);
        vec.shrink_to_fit();

        assert_eq!(vec.as_slice(), &[1, 2, 3]);
        assert!(vec.capacity() < 1024);
    }

    // }}}
    // {{{ Vec-like behavior

    #[test]
    fn test_deref_slice_api() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[3, 1, 2]);

        // Indexing, iteration and the slice methods come from `Deref<Target = [T]>`.
        assert_eq!(vec[0], 3);
        assert_eq!(vec.first(), Some(&3));
        assert_eq!(vec.last(), Some(&2));
        assert!(vec.contains(&1));
        assert_eq!(vec.iter().copied().max(), Some(3));

        vec.sort_unstable();
        assert_eq!(vec.as_slice(), &[1, 2, 3]);
        assert_eq!(vec.binary_search(&2), Ok(1));

        vec[0] = 10;
        assert_eq!(vec.as_slice(), &[10, 2, 3]);
    }

    #[test]
    fn test_collect_and_extend() {
        let mut vec: QVector<'_, u32> = (0..5).collect();

        assert_eq!(vec.as_slice(), &[0, 1, 2, 3, 4]);

        // `Extend<T>`
        vec.extend(5..7);
        assert_eq!(vec.as_slice(), &[0, 1, 2, 3, 4, 5, 6]);

        // `Extend<&T>`
        vec.extend(&[7, 8]);
        assert_eq!(vec.as_slice(), &[0, 1, 2, 3, 4, 5, 6, 7, 8]);
    }

    #[test]
    fn test_iterate_by_reference() {
        let mut vec: QVector<'_, u32> = (0..4).collect();

        assert_eq!((&vec).into_iter().sum::<u32>(), 6);

        for value in &mut vec {
            *value *= 2;
        }
        assert_eq!(vec.as_slice(), &[0, 2, 4, 6]);
    }

    #[test]
    fn test_into_iter() {
        let vec: QVector<'_, u32> = (0..4).collect();

        assert_eq!(vec.into_iter().collect::<Vec<_>>(), vec![0, 1, 2, 3]);

        let vec: QVector<'_, u32> = (0..4).collect();

        assert_eq!(vec.into_iter().rev().collect::<Vec<_>>(), vec![3, 2, 1, 0]);

        let vec: QVector<'_, u32> = (0..4).collect();
        let mut iter = vec.into_iter();

        assert_eq!(iter.len(), 4);
        assert_eq!(iter.next(), Some(0));
        assert_eq!(iter.next_back(), Some(3));
        assert_eq!(iter.as_slice(), &[1, 2]);
        assert_eq!(iter.len(), 2);
    }

    #[test]
    fn test_clone_and_eq() {
        let vec: QVector<'_, u32> = (0..4).collect();
        let clone = vec.clone();

        assert_eq!(vec, clone);
        assert!(vec == [0, 1, 2, 3]);
        assert_eq!(clone.as_slice(), &[0, 1, 2, 3]);
    }

    #[test]
    fn test_debug() {
        let vec: QVector<'_, u32> = (0..3).collect();

        assert_eq!(format!("{vec:?}"), "[0, 1, 2]");
    }

    // }}}
    // {{{ Allocators

    #[test]
    fn test_t_pool() {
        let t_scope = TScope::new_scope();
        let mut vec = QVector::<u32>::t_new(&t_scope);

        for i in 0..1_000 {
            vec.push(i);
        }

        assert_eq!(vec.len(), 1_000);
        assert_eq!(vec.iter().sum::<u32>(), (0..1_000).sum::<u32>());
    }

    #[test]
    fn test_t_with_capacity() {
        let t_scope = TScope::new_scope();
        let mut vec = QVector::<u32>::t_with_capacity(&t_scope, 128);

        assert!(vec.capacity() >= 128);
        vec.extend_from_slice(&[1, 2, 3]);
        assert_eq!(vec.as_slice(), &[1, 2, 3]);
    }

    #[test]
    fn test_t_from_iter() {
        let t_scope = TScope::new_scope();
        let vec = QVector::t_from_iter(&t_scope, 0..5u32);

        assert_eq!(vec.as_slice(), &[0, 1, 2, 3, 4]);
    }

    #[test]
    fn test_from_stack_buffer() {
        let mut buffer = [MaybeUninit::<u32>::uninit(); 4];
        let mut vec = QVector::from_stack_buffer(&mut buffer);

        assert_eq!(vec.capacity(), 4);
        vec.extend_from_slice(&[1, 2, 3, 4]);
        assert_eq!(vec.as_slice(), &[1, 2, 3, 4]);

        // Growing past the buffer falls back to libc.
        vec.push(5);
        assert_eq!(vec.as_slice(), &[1, 2, 3, 4, 5]);
        assert!(vec.capacity() > 4);
    }

    // }}}
    // {{{ Element ownership

    #[test]
    fn test_drop_drops_the_elements() {
        let counter = Cell::new(0);

        {
            let mut vec = QVector::new();

            push_counters(&mut vec, &counter, 3);
            assert_eq!(counter.get(), 0);
        }

        assert_eq!(counter.get(), 3);
    }

    #[test]
    fn test_truncate_drops_the_elements() {
        let counter = Cell::new(0);
        let mut vec = QVector::new();

        push_counters(&mut vec, &counter, 5);

        vec.truncate(2);
        assert_eq!(counter.get(), 3);

        vec.clear();
        assert_eq!(counter.get(), 5);
    }

    #[test]
    fn test_pop_moves_the_element_out() {
        let counter = Cell::new(0);
        let mut vec = QVector::new();

        push_counters(&mut vec, &counter, 2);

        let popped = vec.pop();

        assert_eq!(counter.get(), 0);
        drop(popped);
        assert_eq!(counter.get(), 1);

        drop(vec);
        assert_eq!(counter.get(), 2);
    }

    #[test]
    fn test_remove_moves_the_element_out() {
        let counter = Cell::new(0);
        let mut vec = QVector::new();

        push_counters(&mut vec, &counter, 3);

        drop(vec.remove(1));
        assert_eq!(counter.get(), 1);
        assert_eq!(vec.len(), 2);

        drop(vec.swap_remove(0));
        assert_eq!(counter.get(), 2);

        drop(vec);
        assert_eq!(counter.get(), 3);
    }

    #[test]
    fn test_into_iter_drops_the_remaining_elements() {
        let counter = Cell::new(0);
        let mut vec = QVector::new();

        push_counters(&mut vec, &counter, 5);

        let mut iter = vec.into_iter();

        // Consume two elements, and drop them.
        drop(iter.next());
        drop(iter.next());
        assert_eq!(counter.get(), 2);

        // Dropping the iterator drops the three remaining elements exactly once.
        drop(iter);
        assert_eq!(counter.get(), 5);
    }

    #[test]
    fn test_t_pool_drops_the_elements() {
        let counter = Cell::new(0);
        let t_scope = TScope::new_scope();

        {
            let mut vec = QVector::t_new(&t_scope);

            push_counters(&mut vec, &counter, 3);
        }

        assert_eq!(counter.get(), 3);
    }

    #[test]
    fn test_deep_wipe_with_owned_lstr() {
        // `OwnedUtf8Lstr` wipes its buffer when dropped, so the vector behaves like the C
        // `qv_deep_wipe()`.
        let mut vec = QVector::<OwnedUtf8Lstr>::new();

        vec.push(from_str("hello").dup());
        vec.push(from_str("world").dup());

        assert_eq!(vec.len(), 2);
        assert_eq!(
            vec.iter().map(|lstr| &**lstr).collect::<Vec<_>>(),
            ["hello", "world"]
        );
    }

    // }}}
    // {{{ C interoperability

    #[test]
    fn test_element_types() {
        const fn assert_element<Q, T>()
        where
            Q: QVectorType<Element = T>,
        {
        }

        assert_element::<qv_u32_t, u32>();
        assert_element::<qv_lstr_t, lstr_t>();
        assert_element::<qv_str_t, *mut c_char>();
    }

    #[test]
    fn test_fill_from_c() {
        let input = "one two three";
        let ps = pstream_t::from_bytes(input.as_bytes());
        let mut vec = QVector::<lstr_t>::new();

        // `ps_split()` fills the vector with values borrowed from `input`, so the element type
        // must stay `lstr_t`: the vector only releases its buffer.
        unsafe {
            ps_split(
                ps,
                &raw const ctype_isspace,
                0,
                vec.as_mut_c_ptr::<qv_lstr_t>(),
            );
        }

        assert_eq!(vec.len(), 3);
        assert_eq!(to_strings(&vec), ["one", "two", "three"]);
    }

    #[test]
    fn test_borrow_c() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[1, 2, 3]);

        let c_vec = vec.as_mut_c_ptr::<qv_u32_t>();

        {
            let borrowed = unsafe { QVector::<u32>::borrow_c_mut(&mut *c_vec) };

            assert_eq!(borrowed.as_slice(), &[1, 2, 3]);
            borrowed.push(4);
        }

        // Dropping the borrow must not release the buffer.
        assert_eq!(vec.as_slice(), &[1, 2, 3, 4]);
    }

    #[test]
    fn test_c_vector_derefs_to_a_slice_without_a_copy() {
        let mut c_vec = c_split("one two three");
        let tab = unsafe { c_vec.__bindgen_anon_1.tab };
        let vec = unsafe { QVector::<lstr_t>::borrow_c(&c_vec) };

        // `Deref` gives a slice that points to the buffer of the C vector: no copy.
        let values: &[lstr_t] = vec;

        assert!(ptr::eq(values.as_ptr(), tab));
        assert_eq!(values.len(), 3);
        assert_eq!(to_strings(values), ["one", "two", "three"]);

        // The slice API is available straight on the C vector.
        assert_eq!(vec.first().map(|raw| raw.len), Some(3));
        assert_eq!(vec.iter().map(|raw| raw.len as usize).sum::<usize>(), 11);

        unsafe {
            qvector_wipe(&raw mut c_vec.qv, size_of::<lstr_t>());
        }
    }

    #[test]
    fn test_c_vector_to_rust_vec() {
        let mut c_vec = c_split("one two three");
        let tab = unsafe { c_vec.__bindgen_anon_1.tab };

        {
            let vec = unsafe { QVector::<lstr_t>::borrow_c(&c_vec) };

            // `to_vec()` comes from the slice API and copies the elements into a `Vec`.
            let owned: Vec<lstr_t> = vec.to_vec();

            assert_eq!(owned.len(), 3);
            assert_eq!(to_strings(&owned), ["one", "two", "three"]);

            // The `Vec` has its own buffer, unlike the slice.
            assert!(!ptr::eq(owned.as_ptr(), tab));
        }

        unsafe {
            qvector_wipe(&raw mut c_vec.qv, size_of::<lstr_t>());
        }
    }

    #[test]
    fn test_qvector_into_rust_vec() {
        let mut vec = QVector::<u32>::new();

        vec.extend_from_slice(&[1, 2, 3]);

        // Taking ownership of the elements moves them out of the C buffer.
        let owned: Vec<u32> = vec.into_iter().collect();

        assert_eq!(owned, vec![1, 2, 3]);
    }

    // }}}
}

// }}}
