IOP YAML Documentation
----------------------

This document describes the supported YAML syntax for IOP serialization/deserialization.

== Description

The syntax is based on https://yaml.org/spec/1.2/spec.html[YAML 1.2], but as the full spec
is overly complex, *a lot* of simplifications have been applied, as well as a few custom
improvements.

* No declarations.
* Only alphanumeric keys starting with a letter are allowed: `[a-zA-Z]\w*`.
* Types only allowed for IOP classes.
* No anchors or references (yet, could be added in the future).

== Mapping with IOP concepts

=== Scalars

* Booleans are written `true` or `false`.
* Integers: `154`, `-23`.
* Floating-point numbers: `-15.23`.
** Special values are handled: `.Inf`, `-.Inf`, `.NaN`.
* Null can be expressed with `null` or `~`
* Strings can be written as is in most cases, but must be quoted if:
** it starts with `!`, `&`, `*`, `-`, `"`, `.`, `[` or `{`.
** it contains `:`, `#`, or non printable ascii characters.
* When a string is quoted, some escape codes are handled:
** `\a`, `\b`, `\e`, `\f`, `\n`, `\r`, `\t`, `\v`, `\"` and `\\` for classic
   printf escape codes.
** `\uXX`, `\uYYY` and `\uZZZZ` are interpreted as an UTF-8 code point.

[source,YAML]
----
foo: Yes, I am a valid string
bar: +0.5ab also me
baz: "- I have to be escaped"
addr: "127.0.0.1:80"
----

=== Arrays

Arrays are written with every element on its own line, prefixed by a dash, with the same indentation:

[source,YAML]
----
array:
  - name: foo
    bar: 5
  - name: baz
----

They can also be written inline using `[` and `]`:

[source,YAML]
----
array: [foo, 5, baz]
----

Only a limited subset of data can be used inside this syntax however:
[source,YAML]
----
[
    # Scalars are allowed, but ',' and ']' now ends strings:
    string one,
    "string, two",
    # A key mapping will generate an object with this single mapping:
    key: value,
    # Additional inline sequences can be used:
    [ foo, ~, ],
    # Inline objects can be used:
    { a: b, c: d }
]
----

=== Struct

The fields of the struct should be written out, one of each line, with the same indentation:

[source,YAML]
----
struct:
  foo: 5
  bar: aa
----

An inline syntax can be used as well:

[source,YAML]
----
struct: { foo: 5, bar: aa }
----

See the inline sequence description for which values can be used in the inline syntax.

=== Class

A class has the same syntax as a struct, but must be prefixed by its fullname as a type:

[source,YAML]
----
class: !aaa.bbb.MyClass
  foo: 5
  bar: aa
----

=== Empty/Default value

Sometimes, we simply want to indicate the presence of a field, or to use all default values:

* For a field of type void, the `~` value should be used.
* For an object with no keys, the `{}` syntax must be used.
* For an array with no elements, the `[]` syntax must be used.

[source,YAML]
----
obj:
  voidField: ~
  emptyStruct: {}
  emptyArray: []
----

== Includes

Other YAML files can be included using the `!include` tag:

[source,YAML]
----
obj:
  key: !include foo.yml
----

The YAML data declared in this file will be inlined in place of the `!include <path>`.

WARNING: Only includes from the same directory (or from subdirectories) are allowed.
Includes from absolute paths or from parent directories are rejected, as they cannot be
repacked in the same way safely.
