/*****     THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY !    *****/
#ifndef IS_IOPC_TOKENS_H
#define IS_IOPC_TOKENS_H

#include <lib-common/core.h>

enum iopc_token {
    IOPC_TK_unknown,
    IOPC_TK_ACTIONSCRIPT,
    IOPC_TK_AS,
    IOPC_TK_BOOL,
    IOPC_TK_BYTE,
    IOPC_TK_BYTES,
    IOPC_TK_DOUBLE,
    IOPC_TK_INT,
    IOPC_TK_LONG,
    IOPC_TK_SHORT,
    IOPC_TK_STRING,
    IOPC_TK_UBYTE,
    IOPC_TK_UINT,
    IOPC_TK_ULONG,
    IOPC_TK_USHORT,
    IOPC_TK_XML,
    IOPC_TK_VOID,
};

__attribute__((pure))
enum iopc_token
iopc_get_token(const char *s, int len);

__attribute__((pure))
enum iopc_token
iopc_get_token_ps(pstream_t ps);

static ALWAYS_INLINE enum iopc_token
iopc_get_token_lstr(lstr_t s)
{
    return iopc_get_token(s.s, s.len);
}
#endif /* IS_IOPC_TOKEN_H */
