/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef linux
#  warning "attrs_valid_v5.iop assumed linux alignments"
#endif
#ifndef __x86_64__
#  warning "attrs_valid_v5.iop assumed x86_64 alignments"
#endif

#include "attrs_valid_v5.iop.h"

/* Class attrs_valid_v5.Toto {{{ */

static iop_field_t const attrs_valid_v5__toto__desc_fields[] = {
};
static int const iop__ranges__1[] = {
    0,
};
static const iop_class_attrs_t attrs_valid_v5__toto__class_s = {
    .is_private        = true,
    .class_id          = 0,
};
const iop_struct_t attrs_valid_v5__toto__s = {
    .fullname   = LSTR_IMMED("attrs_valid_v5.Toto"),
    .fields     = attrs_valid_v5__toto__desc_fields,
    .ranges     = iop__ranges__1,
    .ranges_len = countof(iop__ranges__1) / 2,
    .fields_len = countof(attrs_valid_v5__toto__desc_fields),
    .size       = sizeof(attrs_valid_v5__toto__t),
    .flags      = 13,
    .is_union   = false,
    .st_attrs   = NULL,
    .fields_attrs = NULL,
    {
        .class_attrs  = &attrs_valid_v5__toto__class_s,
    }
};
iop_struct_t const * const attrs_valid_v5__toto__sp = &attrs_valid_v5__toto__s;

/* }}} */
/* Package attrs_valid_v5 {{{ */

static const iop_pkg_t *const attrs_valid_v5__deps[] = {
    NULL,
};

static const iop_enum_t *const attrs_valid_v5__enums[] = {
    NULL,
};

static const iop_struct_t *const attrs_valid_v5__structs[] = {
    &attrs_valid_v5__toto__s,
    NULL,
};

static const iop_iface_t *const attrs_valid_v5__ifaces[] = {
    NULL,
};

static const iop_mod_t *const attrs_valid_v5__mods[] = {
    NULL,
};

static const iop_typedef_t *const attrs_valid_v5__td[] = {
    NULL,
};

iop_pkg_t const attrs_valid_v5__pkg = {
    .name     = LSTR_IMMED("attrs_valid_v5"),
    .deps     = attrs_valid_v5__deps,
    .enums    = attrs_valid_v5__enums,
    .structs  = attrs_valid_v5__structs,
    .ifaces   = attrs_valid_v5__ifaces,
    .mods     = attrs_valid_v5__mods,
    .typedefs = attrs_valid_v5__td,
};
iop_pkg_t const * const attrs_valid_v5__pkgp = &attrs_valid_v5__pkg;

/* }}} */

