/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_tstdox_TYPES_H
#define IOP_HEADER_GUARD_tstdox_TYPES_H

#include "tstdox-tdef.iop.h"

#if __has_feature(nullability)
#pragma GCC diagnostic push
#pragma GCC diagnostic error "-Wnullability-completeness"
#endif

EXPORT iop_enum_t const tstdox__my_enum_a__e;
EXPORT iop_enum_t const * const nonnull tstdox__my_enum_a__ep;

EXPORT iop_enum_t const tstdox__my_enum_b__e;
EXPORT iop_enum_t const * const nonnull tstdox__my_enum_b__ep;

EXPORT iop_enum_t const tstdox__my_enum_c__e;
EXPORT iop_enum_t const * const nonnull tstdox__my_enum_c__ep;

EXPORT iop_enum_t const tstdox__my_enum_d__e;
EXPORT iop_enum_t const * const nonnull tstdox__my_enum_d__ep;

struct tstdox__my_struct_a__t {
    int32_t  field_a;
    int32_t  field_b;
    int32_t  field_c;
};
EXPORT iop_struct_t const tstdox__my_struct_a__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_a__sp;
struct tstdox__my_struct_b__t {
    int32_t  i;
    int32_t  j;
};
EXPORT iop_struct_t const tstdox__my_struct_b__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_b__sp;
struct tstdox__c_data_test__t {
    lstr_t   sfield;
};
EXPORT iop_struct_t const tstdox__c_data_test__s;
EXPORT iop_struct_t const * const nonnull tstdox__c_data_test__sp;
struct tstdox__my_struct_aa__t {
    int32_t  field_a;
    int32_t  field_b;
    int32_t  field_c;
};
EXPORT iop_struct_t const tstdox__my_struct_aa__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_aa__sp;
struct tstdox__my_struct_ab__t {
    int32_t  field_a;
    int32_t  field_b;
    int32_t  field_c;
};
EXPORT iop_struct_t const tstdox__my_struct_ab__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_ab__sp;
struct tstdox__my_struct_ac__t {
    int32_t  field_a;
    int32_t  field_b;
    int32_t  field_c;
};
EXPORT iop_struct_t const tstdox__my_struct_ac__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_ac__sp;
struct tstdox__my_struct_ba__t {
    int32_t  i;
    int32_t  j;
};
EXPORT iop_struct_t const tstdox__my_struct_ba__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_ba__sp;
struct tstdox__my_struct_bb__t {
    int32_t  i;
    int32_t  j;
};
EXPORT iop_struct_t const tstdox__my_struct_bb__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_struct_bb__sp;
struct tstdox__sort_field__t {
    uint32_t pos;
};
EXPORT iop_struct_t const tstdox__sort_field__s;
EXPORT iop_struct_t const * const nonnull tstdox__sort_field__sp;
struct tstdox__my_class_base__t {
    const iop_struct_t *nonnull __vptr;
};
EXPORT iop_struct_t const tstdox__my_class_base__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_class_base__sp;
#define tstdox__my_class_base__class_id  0

struct tstdox__my_class_a__t {
    union {
        tstdox__my_class_base__t super;
        struct {
            const iop_struct_t *nonnull __vptr;
            /* fields of tstdox__my_class_base__t */
        };
    };
};
EXPORT iop_struct_t const tstdox__my_class_a__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_class_a__sp;
#define tstdox__my_class_a__class_id  1

struct tstdox__my_class1__t {
    const iop_struct_t *nonnull __vptr;
};
EXPORT iop_struct_t const tstdox__my_class1__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_class1__sp;
#define tstdox__my_class1__class_id  1

struct tstdox__my_class2__t {
    union {
        tstdox__my_class1__t super;
        struct {
            const iop_struct_t *nonnull __vptr;
            /* fields of tstdox__my_class1__t */
        };
    };
};
EXPORT iop_struct_t const tstdox__my_class2__s;
EXPORT iop_struct_t const * const nonnull tstdox__my_class2__sp;
#define tstdox__my_class2__class_id  2

#if __has_feature(nullability)
#pragma GCC diagnostic pop
#endif

#endif
