/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_tstgen_TYPEDEFS_H
#define IOP_HEADER_GUARD_tstgen_TYPEDEFS_H

#include <lib-common/core.h>
#include <lib-common/iop/internals.h>

typedef enum tstgen__my_enum_a__t {
    MY_ENUM_A_VAL_A,
    MY_ENUM_A_VAL_B,
    MY_ENUM_A_VAL_C,
    MY_ENUM_A_ALIAS_C = MY_ENUM_A_VAL_C,
} tstgen__my_enum_a__t;
typedef IOP_ARRAY_OF(enum tstgen__my_enum_a__t) tstgen__my_enum_a__array_t;
#ifdef OPT_OF
typedef OPT_OF(enum tstgen__my_enum_a__t) tstgen__my_enum_a__opt_t;
#else
typedef IOP_OPT_OF(enum tstgen__my_enum_a__t) tstgen__my_enum_a__opt_t;
#endif
#define MY_ENUM_A_count 3
#define MY_ENUM_A_min   0
#define MY_ENUM_A_max   2

typedef struct tstgen__my_struct_a__t tstgen__my_struct_a__t;
typedef IOP_ARRAY_OF(tstgen__my_struct_a__t) tstgen__my_struct_a__array_t;

typedef struct tstgen__my_union_a__t tstgen__my_union_a__t;
typedef IOP_ARRAY_OF(tstgen__my_union_a__t) tstgen__my_union_a__array_t;

typedef struct tstgen__optimized__t tstgen__optimized__t;
typedef IOP_ARRAY_OF(tstgen__optimized__t) tstgen__optimized__array_t;

typedef struct tstgen__my_class_a__t tstgen__my_class_a__t;
typedef IOP_ARRAY_OF(tstgen__my_class_a__t *nonnull ) tstgen__my_class_a__array_t;

#endif
