/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_tstjson_TYPES_H
#define IOP_HEADER_GUARD_tstjson_TYPES_H

#include "tstjson-tdef.iop.h"

#if __has_feature(nullability)
#pragma GCC diagnostic push
#pragma GCC diagnostic error "-Wnullability-completeness"
#endif

EXPORT iop_enum_t const tstjson__my_enum_a__e;
EXPORT iop_enum_t const * const nonnull tstjson__my_enum_a__ep;

typedef tstjson__my_enum_a__t enum_a__t;
typedef tstjson__my_enum_a__array_t enum_a__array_t;
typedef tstjson__my_enum_a__opt_t enum_a__opt_t;
#define enum_a__e  tstjson__my_enum_a__e

EXPORT iop_enum_t const tstjson__my_enum_b__e;
EXPORT iop_enum_t const * const nonnull tstjson__my_enum_b__ep;

EXPORT iop_enum_t const tstjson__my_enum_c__e;
EXPORT iop_enum_t const * const nonnull tstjson__my_enum_c__ep;

/*----- XXX private data, do not use directly -{{{-*/
typedef enum tstjson__my_union_a__tag_t {
    tstjson__my_union_a__i__ft = 1,
    tstjson__my_union_a__b__ft = 2,
    tstjson__my_union_a__s__ft = 3,
} tstjson__my_union_a__tag_t;

#define tstjson__my_union_a__i__fdesc  tstjson__my_union_a__s.fields[0]
#define tstjson__my_union_a__b__fdesc  tstjson__my_union_a__s.fields[1]
#define tstjson__my_union_a__s__fdesc  tstjson__my_union_a__s.fields[2]
/*-}}}-*/
struct tstjson__my_union_a__t {
    tstjson__my_union_a__tag_t iop_tag;
    union {
        int32_t  i;
        int8_t   b;
        lstr_t   s;
    };
};
EXPORT iop_struct_t const tstjson__my_union_a__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_union_a__sp;
#define tstjson__my_union_a__get(u, field)       IOP_UNION_GET(tstjson__my_union_a, u, field)
struct tstjson__my_struct_a__t {
    opt_i32_t        i;
    lstr_t           s;
    tstjson__my_union_a__t u1;
    tstjson__my_union_a__t u2;
    tstjson__my_union_a__t u3;
    int32_t  class;
};
EXPORT iop_struct_t const tstjson__my_struct_a__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_struct_a__sp;
typedef tstjson__my_struct_a__t struct_a__t;
typedef tstjson__my_struct_a__array_t struct_a__array_t;
#define struct_a__s  tstjson__my_struct_a__s

struct tstjson__my_struct_b__t {
    int32_t  a;
    uint32_t b;
    int8_t   c;
    uint8_t  d;
    int16_t  e;
    uint16_t f;
    bool     j;
    int64_t  g;
    uint64_t h;
    double   i;
    lstr_t   k;
    lstr_t   l;
    tstjson__my_enum_a__t m;
    tstjson__my_union_a__array_t union_a;
    tstjson__my_struct_a__t struct_a;
    lstr_t   xml_field;
};
EXPORT iop_struct_t const tstjson__my_struct_b__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_struct_b__sp;
struct tstjson__my_struct_c__t {
    int32_t  a;
    int32_t  b;
};
EXPORT iop_struct_t const tstjson__my_struct_c__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_struct_c__sp;
/*----- XXX private data, do not use directly -{{{-*/
typedef enum tstjson__constraint_u__tag_t {
    tstjson__constraint_u__u8__ft = 1,
    tstjson__constraint_u__u16__ft = 2,
    tstjson__constraint_u__u32__ft = 3,
    tstjson__constraint_u__u64__ft = 4,
    tstjson__constraint_u__s__ft = 5,
} tstjson__constraint_u__tag_t;

#define tstjson__constraint_u__u8__fdesc  tstjson__constraint_u__s.fields[0]
#define tstjson__constraint_u__u16__fdesc  tstjson__constraint_u__s.fields[1]
#define tstjson__constraint_u__u32__fdesc  tstjson__constraint_u__s.fields[2]
#define tstjson__constraint_u__u64__fdesc  tstjson__constraint_u__s.fields[3]
#define tstjson__constraint_u__s__fdesc  tstjson__constraint_u__s.fields[4]
/*-}}}-*/
struct tstjson__constraint_u__t {
    tstjson__constraint_u__tag_t iop_tag;
    union {
        uint8_t  u8;
        uint16_t u16;
        uint32_t u32;
        uint64_t u64;
        lstr_t   s;
    };
};
EXPORT iop_struct_t const tstjson__constraint_u__s;
EXPORT iop_struct_t const * const nonnull tstjson__constraint_u__sp;
#define tstjson__constraint_u__get(u, field)       IOP_UNION_GET(tstjson__constraint_u, u, field)
struct tstjson__constraint_s__t {
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(int8_t)   i8;
#else
    iop_array_i8_t     i8;
#endif
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(int16_t)  i16;
#else
    iop_array_i16_t    i16;
#endif
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(int32_t)  i32;
#else
    iop_array_i32_t    i32;
#endif
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(int64_t)  i64;
#else
    iop_array_i64_t    i64;
#endif
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(lstr_t)   s;
#else
    iop_array_lstr_t   s;
#endif
    lstr_t   s2;
};
EXPORT iop_struct_t const tstjson__constraint_s__s;
EXPORT iop_struct_t const * const nonnull tstjson__constraint_s__sp;
struct tstjson__my_class_base__t {
    const iop_struct_t *nonnull __vptr;
    int32_t  a;
    tstjson__my_struct_a__t struct_a;
};
EXPORT iop_struct_t const tstjson__my_class_base__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_class_base__sp;
#define tstjson__my_class_base__class_id  0

struct tstjson__my_class_a__t {
    union {
        tstjson__my_class_base__t super;
        struct {
            const iop_struct_t *nonnull __vptr;
            /* fields of tstjson__my_class_base__t */
            int32_t  a;
            tstjson__my_struct_a__t struct_a;
        };
    };
    opt_i32_t        b;
    tstjson__my_struct_b__array_t struct_b;
};
EXPORT iop_struct_t const tstjson__my_class_a__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_class_a__sp;
#define tstjson__my_class_a__class_id  1

struct tstjson__my_class_b__t {
    union {
        tstjson__my_class_base__t super;
        struct {
            const iop_struct_t *nonnull __vptr;
            /* fields of tstjson__my_class_base__t */
            int32_t  a;
            tstjson__my_struct_a__t struct_a;
        };
    };
    int32_t  val;
};
EXPORT iop_struct_t const tstjson__my_class_b__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_class_b__sp;
#define tstjson__my_class_b__class_id  2

struct tstjson__my_class1__t {
    const iop_struct_t *nonnull __vptr;
};
EXPORT iop_struct_t const tstjson__my_class1__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_class1__sp;
#define tstjson__my_class1__class_id  1

struct tstjson__my_class2__t {
    union {
        tstjson__my_class1__t super;
        struct {
            const iop_struct_t *nonnull __vptr;
            /* fields of tstjson__my_class1__t */
        };
    };
};
EXPORT iop_struct_t const tstjson__my_class2__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_class2__sp;
#define tstjson__my_class2__class_id  2

struct tstjson__class_container__t {
    tstjson__my_class_a__t *nonnull a;
    tstjson__my_class_b__t *nonnull b;
};
EXPORT iop_struct_t const tstjson__class_container__s;
EXPORT iop_struct_t const * const nonnull tstjson__class_container__sp;
struct tstjson__my_exception_a__t {
    int32_t  errcode;
    lstr_t   desc;
};
EXPORT iop_struct_t const tstjson__my_exception_a__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_exception_a__sp;
#if __has_feature(nullability)
#pragma GCC diagnostic pop
#endif

#endif
