/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_tstjson_H
#define IOP_HEADER_GUARD_tstjson_H

#include "tstjson-t.iop.h"

typedef struct tstjson__my_iface_a__fun_a_args__t tstjson__my_iface_a__fun_a_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_a_args__t) tstjson__my_iface_a__fun_a_args__array_t;

typedef struct tstjson__my_iface_a__fun_a_res__t tstjson__my_iface_a__fun_a_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_a_res__t) tstjson__my_iface_a__fun_a_res__array_t;

typedef iop__void__t tstjson__my_iface_a__fun_a_exn__t;
typedef iop__void__t tstjson__my_iface_a__funb_args__t;
typedef struct tstjson__my_iface_a__funb_res__t tstjson__my_iface_a__funb_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__funb_res__t) tstjson__my_iface_a__funb_res__array_t;

typedef iop__void__t tstjson__my_iface_a__funb_exn__t;
typedef iop__void__t tstjson__my_iface_a__fun_d_args__t;
typedef tstjson__my_struct_a__t tstjson__my_iface_a__fun_d_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_d_exn__t;
typedef tstjson__my_struct_a__t tstjson__my_iface_a__fun_c_args__t;
typedef tstjson__my_struct_b__t tstjson__my_iface_a__fun_c_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_c_exn__t;
typedef struct tstjson__my_iface_a__fun_f_args__t tstjson__my_iface_a__fun_f_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_f_args__t) tstjson__my_iface_a__fun_f_args__array_t;

typedef tstjson__my_struct_b__t tstjson__my_iface_a__fun_f_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_f_exn__t;
typedef iop__void__t tstjson__my_iface_a__fun_g_args__t;
typedef iop__void__t tstjson__my_iface_a__fun_g_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_g_exn__t;
typedef iop__void__t tstjson__my_iface_a__fun_h_args__t;
typedef iop__void__t tstjson__my_iface_a__fun_h_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_h_exn__t;
typedef tstjson__my_union_a__t tstjson__my_iface_a__fun_i_args__t;
typedef iop__void__t tstjson__my_iface_a__fun_i_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_i_exn__t;
typedef tstjson__my_struct_a__t tstjson__my_iface_a__fun_j_args__t;
typedef struct tstjson__my_iface_a__fun_j_res__t tstjson__my_iface_a__fun_j_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_j_res__t) tstjson__my_iface_a__fun_j_res__array_t;

typedef struct tstjson__my_iface_a__fun_j_exn__t tstjson__my_iface_a__fun_j_exn__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_j_exn__t) tstjson__my_iface_a__fun_j_exn__array_t;

typedef iop__void__t tstjson__my_iface_a__fun_e_args__t;
typedef struct tstjson__my_iface_a__fun_e_res__t tstjson__my_iface_a__fun_e_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_e_res__t) tstjson__my_iface_a__fun_e_res__array_t;

typedef iop__void__t tstjson__my_iface_a__fun_e_exn__t;
typedef tstjson__my_struct_a__t tstjson__my_iface_a__fun_k_args__t;
typedef struct tstjson__my_iface_a__fun_k_res__t tstjson__my_iface_a__fun_k_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_k_res__t) tstjson__my_iface_a__fun_k_res__array_t;

typedef tstjson__my_exception_a__t tstjson__my_iface_a__fun_k_exn__t;
typedef struct tstjson__my_iface_a__fun_l_args__t tstjson__my_iface_a__fun_l_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_l_args__t) tstjson__my_iface_a__fun_l_args__array_t;

typedef iop__void__t tstjson__my_iface_a__fun_l_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_l_exn__t;
typedef struct tstjson__my_iface_a__fun_async_args__t tstjson__my_iface_a__fun_async_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_a__fun_async_args__t) tstjson__my_iface_a__fun_async_args__array_t;

typedef iop__void__t tstjson__my_iface_a__fun_async_res__t;
typedef iop__void__t tstjson__my_iface_a__fun_async_exn__t;
typedef struct tstjson__my_iface_b__fun_a_args__t tstjson__my_iface_b__fun_a_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_b__fun_a_args__t) tstjson__my_iface_b__fun_a_args__array_t;

typedef struct tstjson__my_iface_b__fun_a_res__t tstjson__my_iface_b__fun_a_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_b__fun_a_res__t) tstjson__my_iface_b__fun_a_res__array_t;

typedef iop__void__t tstjson__my_iface_b__fun_a_exn__t;
typedef struct tstjson__my_iface_c__fun_a_args__t tstjson__my_iface_c__fun_a_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_c__fun_a_args__t) tstjson__my_iface_c__fun_a_args__array_t;

typedef struct tstjson__my_iface_c__fun_a_res__t tstjson__my_iface_c__fun_a_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_c__fun_a_res__t) tstjson__my_iface_c__fun_a_res__array_t;

typedef iop__void__t tstjson__my_iface_c__fun_a_exn__t;
typedef struct tstjson__my_iface_d__fun_a_args__t tstjson__my_iface_d__fun_a_args__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_d__fun_a_args__t) tstjson__my_iface_d__fun_a_args__array_t;

typedef struct tstjson__my_iface_d__fun_a_res__t tstjson__my_iface_d__fun_a_res__t;
typedef IOP_ARRAY_OF(tstjson__my_iface_d__fun_a_res__t) tstjson__my_iface_d__fun_a_res__array_t;

typedef iop__void__t tstjson__my_iface_d__fun_a_exn__t;

/*----- interface tstjson.MyIfaceA -----*/
struct tstjson__my_iface_a__fun_a_args__t {
    int32_t  a;
    tstjson__my_struct_a__t b;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_a_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_a_args__sp;
struct tstjson__my_iface_a__fun_a_res__t {
    tstjson__my_union_a__t c;
    int32_t  d;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_a_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_a_res__sp;
#define tstjson__my_iface_a__fun_a__rpc__tag    0x0001
#define tstjson__my_iface_a__fun_a__rpc__async  0
#define tstjson__my_iface_a__fun_a__rpc         (tstjson__my_iface_a__if.funs + 0)

struct tstjson__my_iface_a__funb_res__t {
    int32_t  a;
    int8_t   b;
};
EXPORT iop_struct_t const tstjson__my_iface_a__funb_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__funb_res__sp;
#define tstjson__my_iface_a__funb__rpc__tag    0x0002
#define tstjson__my_iface_a__funb__rpc__async  0
#define tstjson__my_iface_a__funb__rpc         (tstjson__my_iface_a__if.funs + 1)

#define tstjson__my_iface_a__fun_d__rpc__tag    0x0003
#define tstjson__my_iface_a__fun_d__rpc__async  0
#define tstjson__my_iface_a__fun_d__rpc         (tstjson__my_iface_a__if.funs + 2)

#define tstjson__my_iface_a__fun_c__rpc__tag    0x0004
#define tstjson__my_iface_a__fun_c__rpc__async  0
#define tstjson__my_iface_a__fun_c__rpc         (tstjson__my_iface_a__if.funs + 3)

struct tstjson__my_iface_a__fun_f_args__t {
#ifndef IOP_ARRAY_T
    IOP_ARRAY_OF(int32_t)  a;
#else
    iop_array_i32_t    a;
#endif
    opt_i32_t        b;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_f_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_f_args__sp;
#define tstjson__my_iface_a__fun_f__rpc__tag    0x0005
#define tstjson__my_iface_a__fun_f__rpc__async  0
#define tstjson__my_iface_a__fun_f__rpc         (tstjson__my_iface_a__if.funs + 4)

#define tstjson__my_iface_a__fun_g__rpc__tag    0x0006
#define tstjson__my_iface_a__fun_g__rpc__async  0
#define tstjson__my_iface_a__fun_g__rpc         (tstjson__my_iface_a__if.funs + 5)

#define tstjson__my_iface_a__fun_h__rpc__tag    0x0007
#define tstjson__my_iface_a__fun_h__rpc__async  0
#define tstjson__my_iface_a__fun_h__rpc         (tstjson__my_iface_a__if.funs + 6)

#define tstjson__my_iface_a__fun_i__rpc__tag    0x0008
#define tstjson__my_iface_a__fun_i__rpc__async  0
#define tstjson__my_iface_a__fun_i__rpc         (tstjson__my_iface_a__if.funs + 7)

struct tstjson__my_iface_a__fun_j_res__t {
    int32_t  a;
    int32_t  b;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_j_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_j_res__sp;
struct tstjson__my_iface_a__fun_j_exn__t {
    int32_t  err;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_j_exn__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_j_exn__sp;
#define tstjson__my_iface_a__fun_j__rpc__tag    0x0009
#define tstjson__my_iface_a__fun_j__rpc__async  0
#define tstjson__my_iface_a__fun_j__rpc         (tstjson__my_iface_a__if.funs + 8)

struct tstjson__my_iface_a__fun_e_res__t {
    opt_i32_t        a;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_e_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_e_res__sp;
#define tstjson__my_iface_a__fun_e__rpc__tag    0x000a
#define tstjson__my_iface_a__fun_e__rpc__async  0
#define tstjson__my_iface_a__fun_e__rpc         (tstjson__my_iface_a__if.funs + 9)

struct tstjson__my_iface_a__fun_k_res__t {
    int32_t  a;
    int32_t  b;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_k_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_k_res__sp;
#define tstjson__my_iface_a__fun_k__rpc__tag    0x000b
#define tstjson__my_iface_a__fun_k__rpc__async  0
#define tstjson__my_iface_a__fun_k__rpc         (tstjson__my_iface_a__if.funs + 10)

struct tstjson__my_iface_a__fun_l_args__t {
    int32_t  a;
    int32_t  b;
    int32_t  c;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_l_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_l_args__sp;
#define tstjson__my_iface_a__fun_l__rpc__tag    0x000c
#define tstjson__my_iface_a__fun_l__rpc__async  0
#define tstjson__my_iface_a__fun_l__rpc         (tstjson__my_iface_a__if.funs + 11)

struct tstjson__my_iface_a__fun_async_args__t {
    int32_t  type;
};
EXPORT iop_struct_t const tstjson__my_iface_a__fun_async_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_a__fun_async_args__sp;
#define tstjson__my_iface_a__fun_async__rpc__tag    0x000d
#define tstjson__my_iface_a__fun_async__rpc__async  1
#define tstjson__my_iface_a__fun_async__rpc         (tstjson__my_iface_a__if.funs + 12)

EXPORT iop_iface_t const tstjson__my_iface_a__if;
EXPORT iop_iface_t const * const nonnull tstjson__my_iface_a__ifp;

/*----- interface tstjson.MyIfaceB -----*/
struct tstjson__my_iface_b__fun_a_args__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_b__fun_a_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_b__fun_a_args__sp;
struct tstjson__my_iface_b__fun_a_res__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_b__fun_a_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_b__fun_a_res__sp;
#define tstjson__my_iface_b__fun_a__rpc__tag    0x0001
#define tstjson__my_iface_b__fun_a__rpc__async  0
#define tstjson__my_iface_b__fun_a__rpc         (tstjson__my_iface_b__if.funs + 0)

EXPORT iop_iface_t const tstjson__my_iface_b__if;
EXPORT iop_iface_t const * const nonnull tstjson__my_iface_b__ifp;

/*----- interface tstjson.MyIfaceC -----*/
struct tstjson__my_iface_c__fun_a_args__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_c__fun_a_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_c__fun_a_args__sp;
struct tstjson__my_iface_c__fun_a_res__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_c__fun_a_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_c__fun_a_res__sp;
#define tstjson__my_iface_c__fun_a__rpc__tag    0x0001
#define tstjson__my_iface_c__fun_a__rpc__async  0
#define tstjson__my_iface_c__fun_a__rpc         (tstjson__my_iface_c__if.funs + 0)

EXPORT iop_iface_t const tstjson__my_iface_c__if;
EXPORT iop_iface_t const * const nonnull tstjson__my_iface_c__ifp;

/*----- interface tstjson.MyIfaceD -----*/
struct tstjson__my_iface_d__fun_a_args__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_d__fun_a_args__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_d__fun_a_args__sp;
struct tstjson__my_iface_d__fun_a_res__t {
    int32_t  i;
};
EXPORT iop_struct_t const tstjson__my_iface_d__fun_a_res__s;
EXPORT iop_struct_t const * const nonnull tstjson__my_iface_d__fun_a_res__sp;
#define tstjson__my_iface_d__fun_a__rpc__tag    0x0001
#define tstjson__my_iface_d__fun_a__rpc__async  0
#define tstjson__my_iface_d__fun_a__rpc         (tstjson__my_iface_d__if.funs + 0)

EXPORT iop_iface_t const tstjson__my_iface_d__if;
EXPORT iop_iface_t const * const nonnull tstjson__my_iface_d__ifp;


/*----- module tstjson.MyModuleA -----*/
#define tstjson__my_module_a__iface_a__TAG    0x0400
#define tstjson__my_module_a__iface_a(a)      tstjson__my_iface_a__##a
#define tstjson__my_module_a__iface_a__alias  (tstjson__my_module_a__mod.ifaces + 0)

#define tstjson__my_module_a__iface_b__TAG    0x0401
#define tstjson__my_module_a__iface_b(a)      tstjson__my_iface_b__##a
#define tstjson__my_module_a__iface_b__alias  (tstjson__my_module_a__mod.ifaces + 1)

EXPORT iop_mod_t const tstjson__my_module_a__mod;
EXPORT iop_mod_t const * const nonnull tstjson__my_module_a__modp;


/*----- module tstjson.MyModuleB -----*/
#define tstjson__my_module_b__iface_c__TAG    0x0200
#define tstjson__my_module_b__iface_c(a)      tstjson__my_iface_c__##a
#define tstjson__my_module_b__iface_c__alias  (tstjson__my_module_b__mod.ifaces + 0)

EXPORT iop_mod_t const tstjson__my_module_b__mod;
EXPORT iop_mod_t const * const nonnull tstjson__my_module_b__modp;


/*----- module tstjson.MyModuleC -----*/
#define tstjson__my_module_c__iface_d__TAG    0x0001
#define tstjson__my_module_c__iface_d(a)      tstjson__my_iface_d__##a
#define tstjson__my_module_c__iface_d__alias  (tstjson__my_module_c__mod.ifaces + 0)

#define tstjson__my_module_c__iface_c__TAG    0x0200
#define tstjson__my_module_c__iface_c(a)      tstjson__my_iface_c__##a
#define tstjson__my_module_c__iface_c__alias  (tstjson__my_module_c__mod.ifaces + 1)

#define tstjson__my_module_c__iface_a2__TAG    0x0300
#define tstjson__my_module_c__iface_a2(a)      tstjson__my_iface_a__##a
#define tstjson__my_module_c__iface_a2__alias  (tstjson__my_module_c__mod.ifaces + 2)

#define tstjson__my_module_c__iface_a__TAG    0x0400
#define tstjson__my_module_c__iface_a(a)      tstjson__my_iface_a__##a
#define tstjson__my_module_c__iface_a__alias  (tstjson__my_module_c__mod.ifaces + 3)

#define tstjson__my_module_c__iface_b__TAG    0x0401
#define tstjson__my_module_c__iface_b(a)      tstjson__my_iface_b__##a
#define tstjson__my_module_c__iface_b__alias  (tstjson__my_module_c__mod.ifaces + 4)

EXPORT iop_mod_t const tstjson__my_module_c__mod;
EXPORT iop_mod_t const * const nonnull tstjson__my_module_c__modp;


/*----- typedef tstjson.MyUnionInt -----*/
EXPORT iop_typedef_t const tstjson__my_union_int__td;
EXPORT iop_typedef_t const * const nonnull tstjson__my_union_int__tdp;


/*----- package tstjson -----*/
EXPORT iop_pkg_t const tstjson__pkg;
EXPORT iop_pkg_t const * const nonnull tstjson__pkgp;

#endif
