/***** THIS FILE IS AUTOGENERATED DO NOT MODIFY DIRECTLY ! *****/
#ifndef IOP_HEADER_GUARD_typedef_valid_TYPEDEFS_H
#define IOP_HEADER_GUARD_typedef_valid_TYPEDEFS_H

#include <lib-common/core.h>
#include <lib-common/iop/internals.h>

typedef struct typedef_valid__my_struct__t typedef_valid__my_struct__t;
typedef IOP_ARRAY_OF(typedef_valid__my_struct__t) typedef_valid__my_struct__array_t;

typedef struct typedef_valid__my_union__t typedef_valid__my_union__t;
typedef IOP_ARRAY_OF(typedef_valid__my_union__t) typedef_valid__my_union__array_t;

typedef struct typedef_valid__a__t typedef_valid__a__t;
typedef IOP_ARRAY_OF(typedef_valid__a__t *nonnull ) typedef_valid__a__array_t;

typedef struct typedef_valid__b__t typedef_valid__b__t;
typedef IOP_ARRAY_OF(typedef_valid__b__t *nonnull ) typedef_valid__b__array_t;

typedef struct typedef_valid__typedef_struct_use_all__t typedef_valid__typedef_struct_use_all__t;
typedef IOP_ARRAY_OF(typedef_valid__typedef_struct_use_all__t) typedef_valid__typedef_struct_use_all__array_t;

typedef struct typedef_valid__typedef_union_use_all__t typedef_valid__typedef_union_use_all__t;
typedef IOP_ARRAY_OF(typedef_valid__typedef_union_use_all__t) typedef_valid__typedef_union_use_all__array_t;

typedef struct typedef_valid__c__t typedef_valid__c__t;
typedef IOP_ARRAY_OF(typedef_valid__c__t *nonnull ) typedef_valid__c__array_t;

typedef struct typedef_valid__routing_hdr__t typedef_valid__routing_hdr__t;
typedef IOP_ARRAY_OF(typedef_valid__routing_hdr__t) typedef_valid__routing_hdr__array_t;

typedef struct typedef_valid__route__t typedef_valid__route__t;
typedef IOP_ARRAY_OF(typedef_valid__route__t *nonnull ) typedef_valid__route__array_t;

typedef struct typedef_valid__hdr__t typedef_valid__hdr__t;
typedef IOP_ARRAY_OF(typedef_valid__hdr__t) typedef_valid__hdr__array_t;

typedef struct typedef_valid__typedef_struct_use_all_with_list__t typedef_valid__typedef_struct_use_all_with_list__t;
typedef IOP_ARRAY_OF(typedef_valid__typedef_struct_use_all_with_list__t) typedef_valid__typedef_struct_use_all_with_list__array_t;

/*----- structure/union for typedef MyStructAlias (from typedef_valid.MyStruct)-----*/
typedef typedef_valid__my_struct__t typedef_valid__my_struct_alias__t;
typedef typedef_valid__my_struct__array_t typedef_valid__my_struct_alias__array_t;
#define typedef_valid__my_struct_alias__s typedef_valid__my_struct__s
#define typedef_valid__my_struct_alias__sp typedef_valid__my_struct__sp

/*----- structure/union for typedef MyUnionAlias (from typedef_valid.MyUnion)-----*/
typedef typedef_valid__my_union__t typedef_valid__my_union_alias__t;
typedef typedef_valid__my_union__array_t typedef_valid__my_union_alias__array_t;
#define typedef_valid__my_union_alias__s typedef_valid__my_union__s
#define typedef_valid__my_union_alias__sp typedef_valid__my_union__sp

/*----- structure/union for typedef MyUnionAB (from typedef_valid.MyUnion)-----*/
typedef typedef_valid__my_union__t typedef_valid__my_union_a_b__t;
typedef typedef_valid__my_union__array_t typedef_valid__my_union_a_b__array_t;
#define typedef_valid__my_union_a_b__s typedef_valid__my_union__s
#define typedef_valid__my_union_a_b__sp typedef_valid__my_union__sp

/*----- structure/union for typedef MyUnionABC (from typedef_valid.MyUnion)-----*/
typedef typedef_valid__my_union__t typedef_valid__my_union_a_b_c__t;
typedef typedef_valid__my_union__array_t typedef_valid__my_union_a_b_c__array_t;
#define typedef_valid__my_union_a_b_c__s typedef_valid__my_union__s
#define typedef_valid__my_union_a_b_c__sp typedef_valid__my_union__sp

/*----- structure/union for typedef MyUnionWithoutC (from typedef_valid.MyUnion)-----*/
typedef typedef_valid__my_union__t typedef_valid__my_union_without_c__t;
typedef typedef_valid__my_union__array_t typedef_valid__my_union_without_c__array_t;
#define typedef_valid__my_union_without_c__s typedef_valid__my_union__s
#define typedef_valid__my_union_without_c__sp typedef_valid__my_union__sp

/*----- structure/union for typedef Adef (from typedef_valid.A)-----*/
typedef typedef_valid__a__t typedef_valid__adef__t;
typedef typedef_valid__a__array_t typedef_valid__adef__array_t;
#define typedef_valid__adef__s typedef_valid__a__s
#define typedef_valid__adef__sp typedef_valid__a__sp

/*----- structure/union for typedef Bdef (from typedef_valid.B)-----*/
typedef typedef_valid__b__t typedef_valid__bdef__t;
typedef typedef_valid__b__array_t typedef_valid__bdef__array_t;
#define typedef_valid__bdef__s typedef_valid__b__s
#define typedef_valid__bdef__sp typedef_valid__b__sp

/*----- structure/union for typedef TypedefRoutingHdr (from typedef_valid.RoutingHdr)-----*/
typedef typedef_valid__routing_hdr__t typedef_valid__typedef_routing_hdr__t;
typedef typedef_valid__routing_hdr__array_t typedef_valid__typedef_routing_hdr__array_t;
#define typedef_valid__typedef_routing_hdr__s typedef_valid__routing_hdr__s
#define typedef_valid__typedef_routing_hdr__sp typedef_valid__routing_hdr__sp

/*----- structure/union for typedef TypedefRoute (from typedef_valid.Route)-----*/
typedef typedef_valid__route__t typedef_valid__typedef_route__t;
typedef typedef_valid__route__array_t typedef_valid__typedef_route__array_t;
#define typedef_valid__typedef_route__s typedef_valid__route__s
#define typedef_valid__typedef_route__sp typedef_valid__route__sp

/*----- structure/union for typedef TypedefHdr (from typedef_valid.Hdr)-----*/
typedef typedef_valid__hdr__t typedef_valid__typedef_hdr__t;
typedef typedef_valid__hdr__array_t typedef_valid__typedef_hdr__array_t;
#define typedef_valid__typedef_hdr__s typedef_valid__hdr__s
#define typedef_valid__typedef_hdr__sp typedef_valid__hdr__sp

/*----- structure/union for typedef TypedefStructUseAllList (from typedef_valid.TypedefStructUseAll)-----*/
typedef typedef_valid__typedef_struct_use_all__t typedef_valid__typedef_struct_use_all_list__t;
typedef typedef_valid__typedef_struct_use_all__array_t typedef_valid__typedef_struct_use_all_list__array_t;
#define typedef_valid__typedef_struct_use_all_list__s typedef_valid__typedef_struct_use_all__s
#define typedef_valid__typedef_struct_use_all_list__sp typedef_valid__typedef_struct_use_all__sp

#endif
