openapi: 3.0.2
info:
  title: zoomin
  version: 0.2.3
  description: sheo
servers:
  - url: "http://localhost:1337/tes"
    description: server description
paths: ~
components:
  schemas: ~
  securitySchemes:
    my_sec:
      type: http
      scheme: basic
security:
  - my_sec: ~
