openapi: 3.0.2
info:
  title: yay
  version: 0.0.1
servers:
  - url: /yay
paths:
  /a/funG:
    post:
      tags:
        - a
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      responses:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
components:
  schemas:
    Void:
      type: object
