openapi: 3.0.2
info:
  title: yay
  version: 0.0.1
components:
  schemas:
    tstiop.Iface.fArgs:
      type: object
      required:
        - i
      properties:
        i:
          type: integer
          format: int32
          minimum: -2147483648
          maximum: 2147483647
    tstiop.Iface.fRes:
      type: object
      required:
        - i
      properties:
        i:
          type: integer
          format: int32
          minimum: -2147483648
          maximum: 2147483647
paths:
  /route/iface/f:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.Iface.fArgs"
      responses:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.Iface.fRes"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
