openapi: 3.0.2
info:
  title: yay
  version: 0.0.1
components:
  schemas: ~
paths:
  /yay/a/funA:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyIfaceA.funAArgs"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funARes"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funb:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funbRes"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funC:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyStructA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyStructB"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funD:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyStructA"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funE:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funERes"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funF:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyIfaceA.funFArgs"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyStructB"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funG:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funH:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funI:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funJ:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Void"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funK:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyStructA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funKRes"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funL:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyUnionA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Void"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funM:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyStructA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funMRes"
        '500':
          description: RPC error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funMExn"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funN:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyStructA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funNRes"
        '500':
          description: RPC error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyAException"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funO:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyStructA"
      response:
        '200':
          description: RPC success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyIfaceA.funORes"
        '500':
          description: RPC error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tstiop.MyExceptions"
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
  /yay/a/funAsync:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tstiop.MyIfaceA.funAsyncArgs"
      response:
        default:
          description: generic error
          content:
            text/html:
              schema:
                type: string
