openapi: 3.0.2
info:
  title: structs
  version: 2.3.1
components:
  schemas:
    tstiop.MyUnionB:
      oneOf:
        - type: object
          required:
            - bval
          properties:
            bval:
              type: integer
              format: int32
              minimum: -2147483648
              maximum: 2147483647
        - type: object
          required:
            - a
          properties:
            a:
              $ref: "#/components/schemas/tstiop.MyUnionA"
    tstiop.MyUnionA:
      oneOf:
        - type: object
          required:
            - ua
          properties:
            ua:
              type: integer
              format: int32
              minimum: -2147483648
              maximum: 2147483647
        - type: object
          required:
            - ub
          properties:
            ub:
              type: integer
              format: int32
              minimum: -128
              maximum: 127
        - type: object
          required:
            - us
          properties:
            us:
              type: string
    tstiop.MyStructJ:
      type: object
      required:
        - cval
        - b
      properties:
        cval:
          type: integer
          format: int32
          minimum: -2147483648
          maximum: 2147483647
        b:
          $ref: "#/components/schemas/tstiop.MyUnionB"
        btab:
          type: array
          items:
            $ref: "#/components/schemas/tstiop.MyUnionB"
    tstiop.MyStructK:
      type: object
      required:
        - j
      properties:
        j:
          $ref: "#/components/schemas/tstiop.MyStructJ"
    tstiop.MyStructM:
      type: object
      required:
        - k
      properties:
        k:
          $ref: "#/components/schemas/tstiop.MyStructK"
paths: ~
